const express = require('express');
const cors = require('cors');
const mongoose = require('mongoose');
require('dotenv').config();
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api', require('./routes/api'));
mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/69bf72d17d2027477f7c1d65').then(() => console.log('DB Connected'));
app.listen(process.env.PORT || 5000, () => console.log('Server running on port 5000'));