import React, { useState, useEffect, useRef } from 'react';
import { ThreeJsConfig } from '../types/LabConfig';

interface Model3DLabProps {
  three_js_config: ThreeJsConfig | null;
  sketchfab_hint: string | null;
  subject: string;
  sensitivity_level: number;
}

// Safe evaluation of simple mathematical expressions generated by LLM
const evaluateExpr = (expr: string, context: Record<string, number>): number => {
  try {
    let sanitized = expr;
    // Replace all variable names in expr with their values from context
    Object.entries(context).forEach(([key, val]) => {
      const regex = new RegExp(`\\b${key}\\b`, 'g');
      sanitized = sanitized.replace(regex, val.toString());
    });
    const fn = new Function(`return (${sanitized})`);
    return fn() || 0;
  } catch (e) {
    console.error("Failed to evaluate expression:", expr, e);
    return 0;
  }
};

export const Model3DLab: React.FC<Model3DLabProps> = ({
  three_js_config,
  sketchfab_hint,
  subject: _subject,
  sensitivity_level,
}) => {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [params, setParams] = useState<Record<string, number>>({});
  const [sketchfabLoading, setSketchfabLoading] = useState(true);
  const animationRef = useRef<number | null>(null);
  const projectileStateRef = useRef({ x: 0, y: 0, vx: 0, vy: 0, t: 0, path: [] as { x: number; y: number }[] });

  // Initialize parameters from config
  useEffect(() => {
    const initialParams: Record<string, number> = {};

    // 1. Initialize from dynamic controls if present
    if (three_js_config?.controls) {
      three_js_config.controls.forEach((control) => {
        initialParams[control.name] = control.defaultValue;
      });
    }

    // 2. Initialize from legacy params config
    if (three_js_config?.params) {
      Object.entries(three_js_config.params).forEach(([key, val]) => {
        if (typeof val === 'number') {
          initialParams[key] = val;
        } else if (typeof val === 'boolean') {
          initialParams[key] = val ? 1 : 0;
        } else {
          initialParams[key] = parseFloat(val) || 0;
        }
      });
    }

    setParams(initialParams);
  }, [three_js_config]);

  // Handle Canvas Render Loop
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas || !three_js_config) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    let width = canvas.width = canvas.clientWidth;
    let height = canvas.height = canvas.clientHeight;

    const resizeObserver = new ResizeObserver(() => {
      if (canvas) {
        width = canvas.width = canvas.clientWidth;
        height = canvas.height = canvas.clientHeight;
      }
    });
    resizeObserver.observe(canvas);

    const type = three_js_config.type;

    // Reset projectile state if type changes
    if (type === 'projectile_motion') {
      const angleRad = ((params.angle || 45) * Math.PI) / 180;
      const speed = params.speed || 20;
      projectileStateRef.current = {
        x: 20,
        y: height - 40,
        vx: speed * Math.cos(angleRad) * 4,
        vy: -speed * Math.sin(angleRad) * 4,
        t: 0,
        path: [],
      };
    }

    const drawGrid = (ctx: CanvasRenderingContext2D, cx: number, cy: number) => {
      ctx.strokeStyle = '#1e1b4b';
      ctx.lineWidth = 1;
      const gridSize = 40;
      for (let x = 0; x < width; x += gridSize) {
        ctx.beginPath();
        ctx.moveTo(x, 0);
        ctx.lineTo(x, height);
        ctx.stroke();
      }
      for (let y = 0; y < height; y += gridSize) {
        ctx.beginPath();
        ctx.moveTo(0, y);
        ctx.lineTo(width, y);
        ctx.stroke();
      }

      // Draw axis
      ctx.strokeStyle = '#4338ca';
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(0, cy);
      ctx.lineTo(width, cy);
      ctx.moveTo(cx, 0);
      ctx.lineTo(cx, height);
      ctx.stroke();
    };

    const render = () => {
      ctx.fillStyle = '#09090b';
      ctx.fillRect(0, 0, width, height);

      const cx = width / 2;
      const cy = height / 2;

      // ─────────────────────────────────────────────
      // DYNAMIC VISUAL ELEMENTS ENGINE
      // ─────────────────────────────────────────────
      if (three_js_config.visual_mapping?.elements) {
        const evalContext: Record<string, number> = { ...params, time: Date.now() * 0.001 };
        
        // Evaluate equations
        const computedOutputs: Record<string, number> = {};
        if (three_js_config.equations) {
          Object.entries(three_js_config.equations).forEach(([outKey, expr]) => {
            computedOutputs[outKey] = evaluateExpr(expr, evalContext);
            evalContext[outKey] = computedOutputs[outKey]; // feed back
          });
        }

        // Draw elements
        three_js_config.visual_mapping.elements.forEach((elem) => {
          const color = elem.color || '#6366f1';
          const size = elem.sizeExpr ? Math.max(2, evaluateExpr(elem.sizeExpr, evalContext)) : 20;
          const speed = elem.speedExpr ? evaluateExpr(elem.speedExpr, evalContext) : 0;
          const glow = elem.glowExpr ? Math.min(1, Math.max(0, evaluateExpr(elem.glowExpr, evalContext))) : 1;

          ctx.save();
          ctx.globalAlpha = glow;

          if (elem.type === 'circle') {
            const x = cx + Math.sin(Date.now() * 0.001 * (speed || 1)) * (cx - size - 20);
            const y = cy;
            ctx.fillStyle = color;
            ctx.beginPath();
            ctx.arc(x, y, size, 0, Math.PI * 2);
            ctx.fill();
            if (elem.label) {
              ctx.fillStyle = '#94a3b8';
              ctx.font = '11px sans-serif';
              ctx.fillText(elem.label, x - size, y + size + 16);
            }
          } 
          else if (elem.type === 'rect') {
            const x = cx - size / 2;
            const y = cy - size / 2;
            ctx.fillStyle = color;
            ctx.fillRect(x, y, size, size);
            if (elem.label) {
              ctx.fillStyle = '#94a3b8';
              ctx.font = '11px sans-serif';
              ctx.fillText(elem.label, x, y - 8);
            }
          }
          else if (elem.type === 'line') {
            ctx.strokeStyle = color;
            ctx.lineWidth = size / 5;
            ctx.beginPath();
            ctx.moveTo(40, cy);
            ctx.lineTo(width - 40, cy);
            ctx.stroke();
          }
          else if (elem.type === 'particles') {
            const particleCount = Math.floor(size);
            const timeSeed = Date.now() * 0.001 * (speed || 1);
            ctx.fillStyle = color;
            for (let i = 0; i < particleCount; i++) {
              const px = ((i * 73 + timeSeed * 80) % (width - 80)) + 40;
              const py = cy + Math.sin(i * 1.7 + timeSeed) * 30;
              ctx.beginPath();
              ctx.arc(px, py, 3 + (i % 3), 0, Math.PI * 2);
              ctx.fill();
            }
          }
          else if (elem.type === 'graph') {
            drawGrid(ctx, cx, cy);
            ctx.strokeStyle = color;
            ctx.lineWidth = 3;
            ctx.beginPath();
            let first = true;
            for (let px = 0; px < width; px++) {
              const x = (px - cx) / 30;
              const y = size * Math.sin((speed || 1) * x - Date.now() * 0.003);
              const py = cy - y * 10;
              if (first) {
                ctx.moveTo(px, py);
                first = false;
              } else {
                ctx.lineTo(px, py);
              }
            }
            ctx.stroke();
          }

          ctx.restore();
        });

        // Info Overlay
        ctx.fillStyle = '#f8fafc';
        ctx.font = 'bold 13px sans-serif';
        let textY = 40;
        if (three_js_config.title) {
          ctx.fillText(three_js_config.title, 25, textY);
          textY += 24;
        }
        ctx.font = '12px monospace';
        Object.entries(computedOutputs).forEach(([key, val]) => {
          const outDef = three_js_config.outputs?.find(o => o.name === key);
          const label = outDef?.label || key;
          const unit = outDef?.unit || '';
          ctx.fillText(`${label}: ${val.toFixed(2)} ${unit}`, 25, textY);
          textY += 18;
        });
      }

      // ─────────────────────────────────────────────
      // LEGACY HARCODED SIMULATIONS FALLBACKS
      // ─────────────────────────────────────────────
      else if (type === 'quadratic_graph') {
        drawGrid(ctx, cx, cy);
        const a = params.a ?? 1;
        const b = params.b ?? 0;
        const c = params.c ?? 0;

        ctx.strokeStyle = '#a855f7';
        ctx.lineWidth = 3;
        ctx.beginPath();
        let first = true;
        for (let px = 0; px < width; px++) {
          const x = (px - cx) / 20;
          const y = a * x * x + b * x + c;
          const py = cy - y * 20;
          if (first) {
            ctx.moveTo(px, py);
            first = false;
          } else {
            ctx.lineTo(px, py);
          }
        }
        ctx.stroke();

        ctx.fillStyle = '#f8fafc';
        ctx.font = '14px monospace';
        ctx.fillText(`y = ${a.toFixed(1)}x² + ${b.toFixed(1)}x + ${c.toFixed(1)}`, 20, 30);
      }
      else if (type === 'linear_graph') {
        drawGrid(ctx, cx, cy);
        const m = params.m ?? 1;
        const cVal = params.c ?? 0;

        ctx.strokeStyle = '#3b82f6';
        ctx.lineWidth = 3;
        ctx.beginPath();
        const y1 = m * (-cx / 20) + cVal;
        const y2 = m * (cx / 20) + cVal;
        ctx.moveTo(0, cy - y1 * 20);
        ctx.lineTo(width, cy - y2 * 20);
        ctx.stroke();

        ctx.fillStyle = '#f8fafc';
        ctx.font = '14px monospace';
        ctx.fillText(`y = ${m.toFixed(1)}x + ${cVal.toFixed(1)}`, 20, 30);
      }
      else if (type === 'trig_graph') {
        drawGrid(ctx, cx, cy);
        const amp = params.amplitude ?? 2;
        const freq = params.frequency ?? 1;

        ctx.strokeStyle = '#06b6d4';
        ctx.lineWidth = 3;
        ctx.beginPath();
        let first = true;
        for (let px = 0; px < width; px++) {
          const x = (px - cx) / 40;
          const y = amp * Math.sin(freq * x);
          const py = cy - y * 40;
          if (first) {
            ctx.moveTo(px, py);
            first = false;
          } else {
            ctx.lineTo(px, py);
          }
        }
        ctx.stroke();

        ctx.fillStyle = '#f8fafc';
        ctx.font = '14px monospace';
        ctx.fillText(`y = ${amp.toFixed(1)} * sin(${freq.toFixed(1)}x)`, 20, 30);
      }
      else if (type === 'normal_distribution') {
        drawGrid(ctx, cx, cy + 40);
        const mean = params.mean ?? 0;
        const std = params.std ?? 1;

        ctx.strokeStyle = '#10b981';
        ctx.lineWidth = 3;
        ctx.beginPath();
        let first = true;
        for (let px = 0; px < width; px++) {
          const x = (px - cx) / 40;
          const diff = x - mean;
          const exponent = -0.5 * (diff * diff) / (std * std);
          const y = (1 / (std * Math.sqrt(2 * Math.PI))) * Math.exp(exponent) * 4;
          const py = (cy + 40) - y * 60;
          if (first) {
            ctx.moveTo(px, py);
            first = false;
          } else {
            ctx.lineTo(px, py);
          }
        }
        ctx.stroke();

        ctx.fillStyle = '#f8fafc';
        ctx.font = '14px monospace';
        ctx.fillText(`Mean = ${mean.toFixed(1)}, StdDev = ${std.toFixed(2)}`, 20, 30);
      }
      else if (type === 'projectile_motion') {
        ctx.strokeStyle = '#334155';
        ctx.lineWidth = 2;
        ctx.beginPath();
        ctx.moveTo(0, height - 40);
        ctx.lineTo(width, height - 40);
        ctx.stroke();

        const state = projectileStateRef.current;
        const gravity = (params.gravity ?? 9.8) * 0.05;

        state.vy += gravity;
        state.x += state.vx * 0.1;
        state.y += state.vy * 0.1;

        if (state.y > height - 40) {
          state.y = height - 40;
          state.vx = 0;
          state.vy = 0;
        } else {
          state.path.push({ x: state.x, y: state.y });
        }

        ctx.strokeStyle = '#f97316';
        ctx.lineWidth = 2;
        ctx.beginPath();
        state.path.forEach((pt, idx) => {
          if (idx === 0) ctx.moveTo(pt.x, pt.y);
          else ctx.lineTo(pt.x, pt.y);
        });
        ctx.stroke();

        ctx.fillStyle = '#f97316';
        ctx.beginPath();
        ctx.arc(state.x, state.y, 8, 0, Math.PI * 2);
        ctx.fill();

        ctx.fillStyle = '#f8fafc';
        ctx.font = '14px monospace';
        ctx.fillText(`Angle: ${params.angle ?? 45}°, Initial Speed: ${params.speed ?? 20} m/s`, 20, 30);

        ctx.fillStyle = '#1e293b';
        ctx.fillRect(width - 120, 20, 100, 30);
        ctx.fillStyle = '#f8fafc';
        ctx.font = '12px sans-serif';
        ctx.fillText('Reset Sim', width - 100, 38);
      }
      else if (type === 'wave_simulation') {
        drawGrid(ctx, cx, cy);
        const amp = params.amplitude ?? 2;
        const freq = params.frequency ?? 1;
        const time = Date.now() * 0.005;

        ctx.strokeStyle = '#e11d48';
        ctx.lineWidth = 3;
        ctx.beginPath();
        let first = true;
        for (let px = 0; px < width; px++) {
          const x = (px - cx) / 40;
          const y = amp * Math.sin(freq * x - time);
          const py = cy - y * 40;
          if (first) {
            ctx.moveTo(px, py);
            first = false;
          } else {
            ctx.lineTo(px, py);
          }
        }
        ctx.stroke();

        ctx.fillStyle = '#f8fafc';
        ctx.font = '14px monospace';
        ctx.fillText(`Wave Simulation: Amp=${amp.toFixed(1)}, Freq=${freq.toFixed(1)}`, 20, 30);
      }
      else if (type === 'ledger_visual') {
        ctx.fillStyle = '#18181b';
        ctx.fillRect(0, 0, width, height);

        ctx.fillStyle = '#fafafa';
        ctx.font = 'bold 16px sans-serif';
        ctx.fillText('Cash Ledger Account', 20, 40);

        ctx.strokeStyle = '#3f3f46';
        ctx.lineWidth = 2;
        ctx.beginPath();
        ctx.moveTo(width / 2, 60);
        ctx.lineTo(width / 2, height - 20);
        ctx.stroke();

        ctx.font = 'bold 14px sans-serif';
        ctx.fillStyle = '#ef4444';
        ctx.fillText('Debit (Dr.)', 40, 80);
        ctx.fillStyle = '#22c55e';
        ctx.fillText('Credit (Cr.)', width / 2 + 40, 80);

        ctx.font = '12px monospace';
        ctx.fillStyle = '#d4d4d8';
        ctx.fillText('01-Apr Capital A/c   $10,000', 40, 110);
        ctx.fillText('05-Apr Sales A/c     $2,500', 40, 130);
        ctx.fillText('12-Apr Commission    $500', 40, 150);

        ctx.fillText('03-Apr Rent Paid     $1,200', width / 2 + 40, 110);
        ctx.fillText('08-Apr Purchase A/c  $4,500', width / 2 + 40, 130);
        ctx.fillText('15-Apr Salary Paid   $2,000', width / 2 + 40, 150);

        ctx.strokeStyle = '#27272a';
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.moveTo(20, 90);
        ctx.lineTo(width - 20, 90);
        ctx.moveTo(20, 160);
        ctx.lineTo(width - 20, 160);
        ctx.stroke();

        ctx.fillStyle = '#e4e4e7';
        ctx.font = 'bold 13px sans-serif';
        ctx.fillText('Total Dr: $13,000', 40, 190);
        ctx.fillText('Total Cr: $7,700', width / 2 + 40, 190);
        ctx.fillStyle = '#3b82f6';
        ctx.fillText('Balance c/d: $5,300', width / 2 + 40, 210);
      }
      else {
        ctx.fillStyle = '#a1a1aa';
        ctx.font = '14px sans-serif';
        ctx.fillText(`Dynamic Simulation: ${type}`, 40, 50);
      }

      animationRef.current = requestAnimationFrame(render);
    };

    render();

    const handleCanvasClick = (e: MouseEvent) => {
      if (type === 'projectile_motion') {
        const rect = canvas.getBoundingClientRect();
        const clickX = e.clientX - rect.left;
        const clickY = e.clientY - rect.top;
        if (clickX >= width - 120 && clickX <= width - 20 && clickY >= 20 && clickY <= 50) {
          const angleRad = ((params.angle || 45) * Math.PI) / 180;
          const speed = params.speed || 20;
          projectileStateRef.current = {
            x: 20,
            y: height - 40,
            vx: speed * Math.cos(angleRad) * 4,
            vy: -speed * Math.sin(angleRad) * 4,
            t: 0,
            path: [],
          };
        }
      }
    };
    canvas.addEventListener('click', handleCanvasClick);

    return () => {
      if (animationRef.current) cancelAnimationFrame(animationRef.current);
      resizeObserver.disconnect();
      if (canvas) canvas.removeEventListener('click', handleCanvasClick);
    };
  }, [three_js_config, params]);

  const handleSliderChange = (key: string, val: number) => {
    setParams((prev) => ({ ...prev, [key]: val }));
  };

  const isSketchfab = sketchfab_hint && sensitivity_level === 0;

  return (
    <div className="w-full h-full flex flex-col bg-zinc-950/60 rounded-xl border border-zinc-800 overflow-hidden backdrop-blur-md">
      {/* Dynamic Lab Guide Description */}
      {three_js_config?.description && (
        <div className="p-3.5 bg-indigo-950/20 border-b border-zinc-800 text-xs text-zinc-300">
          <strong>🔬 Lab Guide: </strong> {three_js_config.description}
        </div>
      )}

      <div className="flex-1 min-h-[300px] relative">
        {isSketchfab ? (
          <div className="w-full h-full relative">
            {sketchfabLoading && (
              <div className="absolute inset-0 flex flex-col items-center justify-center bg-zinc-950 z-10">
                <div className="w-12 h-12 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin"></div>
                <p className="mt-4 text-zinc-400 text-sm">Loading 3D Model from Sketchfab...</p>
              </div>
            )}
            <iframe
              src={`https://sketchfab.com/models/${sketchfab_hint}/embed?autostart=1&ui_theme=dark&preload=1`}
              title="3D Model Viewer"
              className="w-full h-full border-none"
              onLoad={() => setSketchfabLoading(false)}
              allow="autoplay; fullscreen; xr-spatial-tracking"
            />
          </div>
        ) : three_js_config ? (
          <canvas ref={canvasRef} className="w-full h-full block cursor-pointer" />
        ) : (
          <div className="w-full h-full flex flex-col items-center justify-center bg-zinc-950/80">
            <div className="relative w-16 h-16">
              <div className="absolute inset-0 border-2 border-indigo-500/20 rounded-lg"></div>
              <div className="absolute inset-0 border-2 border-t-indigo-500 rounded-lg animate-spin"></div>
            </div>
            <p className="mt-4 text-zinc-400 text-sm font-medium">Virtual 3D Model Loading...</p>
          </div>
        )}
      </div>

      {/* Control sliders */}
      {three_js_config && (
        <div className="p-4 bg-zinc-900/80 border-t border-zinc-800 flex flex-col gap-3">
          {/* 1. Dynamic Sliders */}
          {three_js_config.controls && three_js_config.controls.map((control) => {
            const val = params[control.name] ?? control.defaultValue;
            return (
              <div key={control.name} className="flex flex-col gap-1">
                <div className="flex justify-between text-xs font-semibold text-zinc-400">
                  <span>{control.label}</span>
                  <span className="text-indigo-400 font-mono">
                    {val.toFixed(1)} {control.unit || ''}
                  </span>
                </div>
                <input
                  type="range"
                  min={control.min}
                  max={control.max}
                  step={control.step}
                  value={val}
                  onChange={(e) => handleSliderChange(control.name, parseFloat(e.target.value))}
                  className="w-full h-1.5 bg-zinc-700 rounded-lg appearance-none cursor-pointer accent-indigo-500"
                />
              </div>
            );
          })}

          {/* 2. Legacy fallback sliders */}
          {!three_js_config.controls && three_js_config.sliders && three_js_config.sliders.map((sliderKey) => {
            let min = 0;
            let max = 100;
            let step = 1;
            let label = sliderKey;

            if (sliderKey === 'a') { min = -5; max = 5; step = 0.1; label = 'Curvature (a)' }
            else if (sliderKey === 'b') { min = -10; max = 10; step = 0.5; label = 'Slope offset (b)' }
            else if (sliderKey === 'c') { min = -10; max = 10; step = 0.5; label = 'Y-Intercept (c)' }
            else if (sliderKey === 'm') { min = -5; max = 5; step = 0.1; label = 'Slope (m)' }
            else if (sliderKey === 'amplitude') { min = 0.5; max = 4; step = 0.1; label = 'Amplitude (A)' }
            else if (sliderKey === 'frequency') { min = 0.2; max = 5; step = 0.1; label = 'Frequency (f)' }
            else if (sliderKey === 'mean') { min = -5; max = 5; step = 0.1; label = 'Mean (μ)' }
            else if (sliderKey === 'std') { min = 0.2; max = 3; step = 0.1; label = 'Standard Deviation (σ)' }
            else if (sliderKey === 'angle') { min = 10; max = 80; step = 1; label = 'Launch Angle (θ)' }
            else if (sliderKey === 'speed') { min = 5; max = 45; step = 1; label = 'Initial Speed (v)' }
            else if (sliderKey === 'gravity') { min = 2; max = 25; step = 0.2; label = 'Gravity (g)' }
            else if (sliderKey === 'voltage') { min = 2; max = 24; step = 1; label = 'Voltage (V)' }
            else if (sliderKey === 'resistance') { min = 1; max = 20; step = 0.5; label = 'Resistance (R)' }

            const val = params[sliderKey] ?? 0;

            return (
              <div key={sliderKey} className="flex flex-col gap-1">
                <div className="flex justify-between text-xs font-semibold text-zinc-400">
                  <span>{label}</span>
                  <span className="text-indigo-400 font-mono">{val.toFixed(1)}</span>
                </div>
                <input
                  type="range"
                  min={min}
                  max={max}
                  step={step}
                  value={val}
                  onChange={(e) => handleSliderChange(sliderKey, parseFloat(e.target.value))}
                  className="w-full h-1.5 bg-zinc-700 rounded-lg appearance-none cursor-pointer accent-indigo-500"
                />
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
