import React, { useState, useEffect, useRef } from 'react';
import { ThreeJsConfig } from '../types/LabConfig';

interface Model3DLabProps {
  three_js_config: ThreeJsConfig | null;
  sketchfab_hint: string | null;
  subject: string;
  sensitivity_level: number;
}

// Safe evaluation of simple mathematical expressions generated by LLM
const evaluateExpr = (expr: string, context: Record<string, number>): number => {
  try {
    let sanitized = expr;
    // Replace all variable names in expr with their values from context
    Object.entries(context).forEach(([key, val]) => {
      const regex = new RegExp(`\\b${key}\\b`, 'g');
      sanitized = sanitized.replace(regex, val.toString());
    });
    const fn = new Function(`return (${sanitized})`);
    return fn() || 0;
  } catch (e) {
    console.error("Failed to evaluate expression:", expr, e);
    return 0;
  }
};

export const Model3DLab: React.FC<Model3DLabProps> = ({
  three_js_config,
  sketchfab_hint,
  subject: _subject,
  sensitivity_level: _sensitivity_level,
}) => {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [params, setParams] = useState<Record<string, number>>({});
  const [sketchfabLoading, setSketchfabLoading] = useState(true);
  const [activeModelId, setActiveModelId] = useState<string | null>(sketchfab_hint);
  const [show2DInterpretation, setShow2DInterpretation] = useState(false);
  const [selectedPart, setSelectedPart] = useState<string | null>(null);
  const mouseRef = useRef({ x: 0, y: 0, click: false, clickX: 0, clickY: 0 });
  const animationRef = useRef<number | null>(null);
  const projectileStateRef = useRef({ x: 0, y: 0, vx: 0, vy: 0, t: 0, path: [] as { x: number; y: number }[] });

  useEffect(() => {
    if (sketchfab_hint === '3d6e5d8a9e7f4c17b5f00e28f3a38ca4' || !sketchfab_hint) {
      setSketchfabLoading(true);
      const token = localStorage.getItem('fbrts_token');
      const searchQuery = three_js_config?.title || _subject || 'science';
      fetch(`/api/future-education/lab/sketchfab-search?query=${encodeURIComponent(searchQuery)}`, {
        headers: { 'Authorization': `Bearer ${token}` }
      })
        .then(r => r.json())
        .then(data => {
          if (data.success && data.model_id) {
            setActiveModelId(data.model_id);
          } else {
            setActiveModelId('8f3b207555804362a26563604f37803a'); // Verified Working DNA model
          }
        })
        .catch(err => {
          console.error('Sketchfab dynamic search failed:', err);
          setActiveModelId('8f3b207555804362a26563604f37803a');
        });
    } else {
      setActiveModelId(sketchfab_hint);
    }
  }, [sketchfab_hint, three_js_config, _subject]);

  // Initialize parameters from config
  useEffect(() => {
    const initialParams: Record<string, number> = {};

    // 1. Initialize from dynamic controls if present
    if (three_js_config?.controls) {
      three_js_config.controls.forEach((control) => {
        initialParams[control.name] = control.defaultValue;
      });
    }

    // 2. Initialize from legacy params config
    if (three_js_config?.params) {
      Object.entries(three_js_config.params).forEach(([key, val]) => {
        if (typeof val === 'number') {
          initialParams[key] = val;
        } else if (typeof val === 'boolean') {
          initialParams[key] = val ? 1 : 0;
        } else {
          initialParams[key] = parseFloat(val) || 0;
        }
      });
    }

    setParams(initialParams);
  }, [three_js_config]);

  // Handle Canvas Render Loop
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas || (!three_js_config && !show2DInterpretation)) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const handleMouseMove = (e: MouseEvent) => {
      const rect = canvas.getBoundingClientRect();
      mouseRef.current.x = e.clientX - rect.left;
      mouseRef.current.y = e.clientY - rect.top;
    };

    const handleMouseClick = (e: MouseEvent) => {
      const rect = canvas.getBoundingClientRect();
      mouseRef.current.click = true;
      mouseRef.current.clickX = e.clientX - rect.left;
      mouseRef.current.clickY = e.clientY - rect.top;
    };

    canvas.addEventListener('mousemove', handleMouseMove);
    canvas.addEventListener('click', handleMouseClick);

    let width = canvas.width = canvas.clientWidth;
    let height = canvas.height = canvas.clientHeight;

    const resizeObserver = new ResizeObserver(() => {
      if (canvas) {
        width = canvas.width = canvas.clientWidth;
        height = canvas.height = canvas.clientHeight;
      }
    });
    resizeObserver.observe(canvas);

    const type = three_js_config?.type;

    // Reset projectile state if type changes
    if (type === 'projectile_motion') {
      const angleRad = ((params.angle || 45) * Math.PI) / 180;
      const speed = params.speed || 20;
      projectileStateRef.current = {
        x: 20,
        y: height - 40,
        vx: speed * Math.cos(angleRad) * 4,
        vy: -speed * Math.sin(angleRad) * 4,
        t: 0,
        path: [],
      };
    }

    const drawGrid = (ctx: CanvasRenderingContext2D, cx: number, cy: number) => {
      ctx.strokeStyle = '#1e1b4b';
      ctx.lineWidth = 1;
      const gridSize = 40;
      for (let x = 0; x < width; x += gridSize) {
        ctx.beginPath();
        ctx.moveTo(x, 0);
        ctx.lineTo(x, height);
        ctx.stroke();
      }
      for (let y = 0; y < height; y += gridSize) {
        ctx.beginPath();
        ctx.moveTo(0, y);
        ctx.lineTo(width, y);
        ctx.stroke();
      }

      // Draw axis
      ctx.strokeStyle = '#4338ca';
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(0, cy);
      ctx.lineTo(width, cy);
      ctx.moveTo(cx, 0);
      ctx.lineTo(cx, height);
      ctx.stroke();
    };

    const render = () => {
      ctx.fillStyle = '#09090b';
      ctx.fillRect(0, 0, width, height);

      const cx = width / 2;
      const cy = height / 2;

      // ─────────────────────────────────────────────
      // DYNAMIC VISUAL ELEMENTS ENGINE
      // ─────────────────────────────────────────────
      if (three_js_config?.visual_mapping?.elements) {
        const evalContext: Record<string, number> = { ...params, time: Date.now() * 0.001 };
        
        // Evaluate equations
        const computedOutputs: Record<string, number> = {};
        if (three_js_config.equations) {
          Object.entries(three_js_config.equations).forEach(([outKey, expr]) => {
            computedOutputs[outKey] = evaluateExpr(expr, evalContext);
            evalContext[outKey] = computedOutputs[outKey]; // feed back
          });
        }

        // Draw elements
        three_js_config.visual_mapping.elements.forEach((elem) => {
          const color = elem.color || '#6366f1';
          const size = elem.sizeExpr ? Math.max(2, evaluateExpr(elem.sizeExpr, evalContext)) : 20;
          const speed = elem.speedExpr ? evaluateExpr(elem.speedExpr, evalContext) : 0;
          const glow = elem.glowExpr ? Math.min(1, Math.max(0, evaluateExpr(elem.glowExpr, evalContext))) : 1;

          ctx.save();
          ctx.globalAlpha = glow;

          if (elem.type === 'circle') {
            const x = cx + Math.sin(Date.now() * 0.001 * (speed || 1)) * (cx - size - 20);
            const y = cy;
            ctx.fillStyle = color;
            ctx.beginPath();
            ctx.arc(x, y, size, 0, Math.PI * 2);
            ctx.fill();
            if (elem.label) {
              ctx.fillStyle = '#94a3b8';
              ctx.font = '11px sans-serif';
              ctx.fillText(elem.label, x - size, y + size + 16);
            }
          } 
          else if (elem.type === 'rect') {
            const x = cx - size / 2;
            const y = cy - size / 2;
            ctx.fillStyle = color;
            ctx.fillRect(x, y, size, size);
            if (elem.label) {
              ctx.fillStyle = '#94a3b8';
              ctx.font = '11px sans-serif';
              ctx.fillText(elem.label, x, y - 8);
            }
          }
          else if (elem.type === 'line') {
            ctx.strokeStyle = color;
            ctx.lineWidth = size / 5;
            ctx.beginPath();
            ctx.moveTo(40, cy);
            ctx.lineTo(width - 40, cy);
            ctx.stroke();
          }
          else if (elem.type === 'particles') {
            const particleCount = Math.floor(size);
            const timeSeed = Date.now() * 0.001 * (speed || 1);
            ctx.fillStyle = color;
            for (let i = 0; i < particleCount; i++) {
              const px = ((i * 73 + timeSeed * 80) % (width - 80)) + 40;
              const py = cy + Math.sin(i * 1.7 + timeSeed) * 30;
              ctx.beginPath();
              ctx.arc(px, py, 3 + (i % 3), 0, Math.PI * 2);
              ctx.fill();
            }
          }
          else if (elem.type === 'graph') {
            drawGrid(ctx, cx, cy);
            ctx.strokeStyle = color;
            ctx.lineWidth = 3;
            ctx.beginPath();
            let first = true;
            for (let px = 0; px < width; px++) {
              const x = (px - cx) / 30;
              const y = size * Math.sin((speed || 1) * x - Date.now() * 0.003);
              const py = cy - y * 10;
              if (first) {
                ctx.moveTo(px, py);
                first = false;
              } else {
                ctx.lineTo(px, py);
              }
            }
            ctx.stroke();
          }

          ctx.restore();
        });

        // Info Overlay
        ctx.fillStyle = '#f8fafc';
        ctx.font = 'bold 13px sans-serif';
        let textY = 40;
        if (three_js_config?.title) {
          ctx.fillText(three_js_config.title, 25, textY);
          textY += 24;
        }
        ctx.font = '12px monospace';
        Object.entries(computedOutputs).forEach(([key, val]) => {
          const outDef = three_js_config?.outputs?.find(o => o.name === key);
          const label = outDef?.label || key;
          const unit = outDef?.unit || '';
          ctx.fillText(`${label}: ${val.toFixed(2)} ${unit}`, 25, textY);
          textY += 18;
        });
      }

      // ─────────────────────────────────────────────
      // LEGACY HARCODED SIMULATIONS FALLBACKS
      // ─────────────────────────────────────────────
      else if (type === 'quadratic_graph') {
        drawGrid(ctx, cx, cy);
        const a = params.a ?? 1;
        const b = params.b ?? 0;
        const c = params.c ?? 0;

        ctx.strokeStyle = '#a855f7';
        ctx.lineWidth = 3;
        ctx.beginPath();
        let first = true;
        for (let px = 0; px < width; px++) {
          const x = (px - cx) / 20;
          const y = a * x * x + b * x + c;
          const py = cy - y * 20;
          if (first) {
            ctx.moveTo(px, py);
            first = false;
          } else {
            ctx.lineTo(px, py);
          }
        }
        ctx.stroke();

        ctx.fillStyle = '#f8fafc';
        ctx.font = '14px monospace';
        ctx.fillText(`y = ${a.toFixed(1)}x² + ${b.toFixed(1)}x + ${c.toFixed(1)}`, 20, 30);
      }
      else if (type === 'linear_graph') {
        drawGrid(ctx, cx, cy);
        const m = params.m ?? 1;
        const cVal = params.c ?? 0;

        ctx.strokeStyle = '#3b82f6';
        ctx.lineWidth = 3;
        ctx.beginPath();
        const y1 = m * (-cx / 20) + cVal;
        const y2 = m * (cx / 20) + cVal;
        ctx.moveTo(0, cy - y1 * 20);
        ctx.lineTo(width, cy - y2 * 20);
        ctx.stroke();

        ctx.fillStyle = '#f8fafc';
        ctx.font = '14px monospace';
        ctx.fillText(`y = ${m.toFixed(1)}x + ${cVal.toFixed(1)}`, 20, 30);
      }
      else if (type === 'trig_graph') {
        drawGrid(ctx, cx, cy);
        const amp = params.amplitude ?? 2;
        const freq = params.frequency ?? 1;

        ctx.strokeStyle = '#06b6d4';
        ctx.lineWidth = 3;
        ctx.beginPath();
        let first = true;
        for (let px = 0; px < width; px++) {
          const x = (px - cx) / 40;
          const y = amp * Math.sin(freq * x);
          const py = cy - y * 40;
          if (first) {
            ctx.moveTo(px, py);
            first = false;
          } else {
            ctx.lineTo(px, py);
          }
        }
        ctx.stroke();

        ctx.fillStyle = '#f8fafc';
        ctx.font = '14px monospace';
        ctx.fillText(`y = ${amp.toFixed(1)} * sin(${freq.toFixed(1)}x)`, 20, 30);
      }
      else if (type === 'normal_distribution') {
        drawGrid(ctx, cx, cy + 40);
        const mean = params.mean ?? 0;
        const std = params.std ?? 1;

        ctx.strokeStyle = '#10b981';
        ctx.lineWidth = 3;
        ctx.beginPath();
        let first = true;
        for (let px = 0; px < width; px++) {
          const x = (px - cx) / 40;
          const diff = x - mean;
          const exponent = -0.5 * (diff * diff) / (std * std);
          const y = (1 / (std * Math.sqrt(2 * Math.PI))) * Math.exp(exponent) * 4;
          const py = (cy + 40) - y * 60;
          if (first) {
            ctx.moveTo(px, py);
            first = false;
          } else {
            ctx.lineTo(px, py);
          }
        }
        ctx.stroke();

        ctx.fillStyle = '#f8fafc';
        ctx.font = '14px monospace';
        ctx.fillText(`Mean = ${mean.toFixed(1)}, StdDev = ${std.toFixed(2)}`, 20, 30);
      }
      else if (type === 'projectile_motion') {
        ctx.strokeStyle = '#334155';
        ctx.lineWidth = 2;
        ctx.beginPath();
        ctx.moveTo(0, height - 40);
        ctx.lineTo(width, height - 40);
        ctx.stroke();

        const state = projectileStateRef.current;
        const gravity = (params.gravity ?? 9.8) * 0.05;

        state.vy += gravity;
        state.x += state.vx * 0.1;
        state.y += state.vy * 0.1;

        if (state.y > height - 40) {
          state.y = height - 40;
          state.vx = 0;
          state.vy = 0;
        } else {
          state.path.push({ x: state.x, y: state.y });
        }

        ctx.strokeStyle = '#f97316';
        ctx.lineWidth = 2;
        ctx.beginPath();
        state.path.forEach((pt, idx) => {
          if (idx === 0) ctx.moveTo(pt.x, pt.y);
          else ctx.lineTo(pt.x, pt.y);
        });
        ctx.stroke();

        ctx.fillStyle = '#f97316';
        ctx.beginPath();
        ctx.arc(state.x, state.y, 8, 0, Math.PI * 2);
        ctx.fill();

        ctx.fillStyle = '#f8fafc';
        ctx.font = '14px monospace';
        ctx.fillText(`Angle: ${params.angle ?? 45}°, Initial Speed: ${params.speed ?? 20} m/s`, 20, 30);

        ctx.fillStyle = '#1e293b';
        ctx.fillRect(width - 120, 20, 100, 30);
        ctx.fillStyle = '#f8fafc';
        ctx.font = '12px sans-serif';
        ctx.fillText('Reset Sim', width - 100, 38);
      }
      else if (type === 'wave_simulation') {
        drawGrid(ctx, cx, cy);
        const amp = params.amplitude ?? 2;
        const freq = params.frequency ?? 1;
        const time = Date.now() * 0.005;

        ctx.strokeStyle = '#e11d48';
        ctx.lineWidth = 3;
        ctx.beginPath();
        let first = true;
        for (let px = 0; px < width; px++) {
          const x = (px - cx) / 40;
          const y = amp * Math.sin(freq * x - time);
          const py = cy - y * 40;
          if (first) {
            ctx.moveTo(px, py);
            first = false;
          } else {
            ctx.lineTo(px, py);
          }
        }
        ctx.stroke();

        ctx.fillStyle = '#f8fafc';
        ctx.font = '14px monospace';
        ctx.fillText(`Wave Simulation: Amp=${amp.toFixed(1)}, Freq=${freq.toFixed(1)}`, 20, 30);
      }
      else if (type === 'ledger_visual') {
        ctx.fillStyle = '#18181b';
        ctx.fillRect(0, 0, width, height);

        ctx.fillStyle = '#fafafa';
        ctx.font = 'bold 16px sans-serif';
        ctx.fillText('Cash Ledger Account', 20, 40);

        ctx.strokeStyle = '#3f3f46';
        ctx.lineWidth = 2;
        ctx.beginPath();
        ctx.moveTo(width / 2, 60);
        ctx.lineTo(width / 2, height - 20);
        ctx.stroke();

        ctx.font = 'bold 14px sans-serif';
        ctx.fillStyle = '#ef4444';
        ctx.fillText('Debit (Dr.)', 40, 80);
        ctx.fillStyle = '#22c55e';
        ctx.fillText('Credit (Cr.)', width / 2 + 40, 80);

        ctx.font = '12px monospace';
        ctx.fillStyle = '#d4d4d8';
        ctx.fillText('01-Apr Capital A/c   $10,000', 40, 110);
        ctx.fillText('05-Apr Sales A/c     $2,500', 40, 130);
        ctx.fillText('12-Apr Commission    $500', 40, 150);

        ctx.fillText('03-Apr Rent Paid     $1,200', width / 2 + 40, 110);
        ctx.fillText('08-Apr Purchase A/c  $4,500', width / 2 + 40, 130);
        ctx.fillText('15-Apr Salary Paid   $2,000', width / 2 + 40, 150);

        ctx.strokeStyle = '#27272a';
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.moveTo(20, 90);
        ctx.lineTo(width - 20, 90);
        ctx.moveTo(20, 160);
        ctx.lineTo(width - 20, 160);
        ctx.stroke();

        ctx.fillStyle = '#e4e4e7';
        ctx.font = 'bold 13px sans-serif';
        ctx.fillText('Total Dr: $13,000', 40, 190);
        ctx.fillText('Total Cr: $7,700', width / 2 + 40, 190);
        ctx.fillStyle = '#3b82f6';
        ctx.fillText('Balance c/d: $5,300', width / 2 + 40, 210);
      }
      else if (type === 'molecule_builder' || type === 'chemical_reaction') {
        drawGrid(ctx, cx, cy + 40);

        const pour = params.pour ?? 0;
        const temp = params.temperature ?? 25;
        const bubbleSpeed = 1 + temp * 0.05;

        // Beaker 1 (Left: Pouring)
        ctx.strokeStyle = '#e2e8f0';
        ctx.lineWidth = 4;
        
        ctx.save();
        const b1x = cx - 120;
        const b1y = cy + 50;
        ctx.translate(b1x, b1y);
        
        const tiltAngle = (pour * 45 / 100) * Math.PI / 180;
        ctx.rotate(tiltAngle);
        
        // Draw beaker 1
        ctx.beginPath();
        ctx.moveTo(-30, -40);
        ctx.lineTo(-30, 40);
        ctx.lineTo(30, 40);
        ctx.lineTo(30, -40);
        ctx.stroke();
        
        const liquidHeight = Math.max(0, 50 - (pour * 0.5));
        ctx.fillStyle = '#38bdf8'; 
        ctx.fillRect(-28, 40 - liquidHeight, 56, liquidHeight);
        ctx.restore();

        // Pouring liquid stream
        if (pour > 5) {
          ctx.strokeStyle = '#38bdf8';
          ctx.lineWidth = 4;
          ctx.beginPath();
          const startX = b1x + 20 + (pour * 0.2);
          const startY = b1y - 10 + (pour * 0.1);
          const endX = cx + 80;
          const endY = cy + 40;
          
          ctx.moveTo(startX, startY);
          ctx.quadraticCurveTo((startX + endX) / 2, startY + 50, endX, endY);
          ctx.stroke();
        }

        // Beaker 2 (Right: Receiving)
        const b2x = cx + 80;
        const b2y = cy + 50;
        ctx.save();
        ctx.translate(b2x, b2y);
        
        ctx.strokeStyle = '#e2e8f0';
        ctx.lineWidth = 4;
        ctx.beginPath();
        ctx.moveTo(-40, -50);
        ctx.lineTo(-40, 50);
        ctx.lineTo(40, 50);
        ctx.lineTo(40, -50);
        ctx.stroke();
        
        const recHeight = Math.min(80, 20 + (pour * 0.6));
        
        // Color transition from green-ish to pink/purple reaction product
        const r = Math.floor(16 + (pour * 2.2));
        const g = Math.floor(185 - (pour * 1.5));
        const b = Math.floor(129 + (pour * 0.5));
        ctx.fillStyle = `rgb(${r}, ${g}, ${b})`;
        ctx.fillRect(-38, 50 - recHeight, 76, recHeight);

        // Bubbles
        ctx.fillStyle = 'rgba(255, 255, 255, 0.4)';
        const bubbleCount = Math.floor(pour * 0.3 * bubbleSpeed);
        const timeSeed = Date.now() * 0.003;
        for (let i = 0; i < bubbleCount; i++) {
          const bx = Math.sin(i * 4.3 + timeSeed) * 30;
          const by = 50 - ((i * 12 + timeSeed * 30 * bubbleSpeed) % recHeight);
          if (by > 50 - recHeight) {
            ctx.beginPath();
            ctx.arc(bx, by, 2 + (i % 3), 0, Math.PI * 2);
            ctx.fill();
          }
        }
        ctx.restore();

        // Info
        ctx.fillStyle = '#fafafa';
        ctx.font = 'bold 15px sans-serif';
        ctx.fillText('Interactive Chemical Reaction Lab', 25, 40);
        
        ctx.font = '12px monospace';
        ctx.fillStyle = '#a1a1aa';
        ctx.fillText('Equation: H₂O (Liquid) + CO₂ (Gas) ⇌ H₂CO₃ (Carbonic Acid)', 25, 70);
        ctx.fillText(`Reaction Temp: ${temp}°C`, 25, 90);
        ctx.fillText(`Pouring State: ${pour.toFixed(0)}%`, 25, 110);
        
        if (pour > 80) {
          ctx.fillStyle = '#f43f5e';
          ctx.font = 'bold 12px sans-serif';
          ctx.fillText('✨ Reaction Complete: Carbonic Acid Formed!', 25, 140);
        } else if (pour > 10) {
          ctx.fillStyle = '#f59e0b';
          ctx.font = 'bold 12px sans-serif';
          ctx.fillText('⚡ Reacting: Synthesizing Carbonic Acid...', 25, 140);
        } else {
          ctx.fillStyle = '#3b82f6';
          ctx.font = 'bold 12px sans-serif';
          ctx.fillText('ℹ️ Use "Pour Amount" slider to start reaction.', 25, 140);
        }
      }
      else {
        // Draw interactive fallback
        ctx.fillStyle = '#06050b';
        ctx.fillRect(0, 0, width, height);

        // Grid background
        drawGrid(ctx, cx, cy);

        const lowerSubject = _subject.toLowerCase();
        const lowerTitle = (three_js_config?.title || sketchfab_hint || '').toLowerCase();
        
        if (lowerSubject.includes('biology') || lowerSubject.includes('fungi') || lowerSubject.includes('life') || lowerTitle.includes('fungi') || lowerTitle.includes('mushroom')) {
          // --- BIOLOGY/FUNGI INTERACTIVE SIMULATION ---
          const mx = cx;
          const my = cy + 40;
          
          // Draw mycelium roots underground (flowing lines)
          ctx.strokeStyle = '#3f3f46';
          ctx.lineWidth = 3;
          ctx.beginPath();
          ctx.moveTo(mx - 150, my + 80);
          ctx.lineTo(mx + 150, my + 80);
          ctx.stroke();

          // Mycelium roots branching
          const time = Date.now() * 0.002;
          ctx.strokeStyle = '#818cf8';
          ctx.lineWidth = 1.5;
          for (let i = 0; i < 8; i++) {
            ctx.beginPath();
            ctx.moveTo(mx + (i - 3.5) * 15, my + 80);
            let rx = mx + (i - 3.5) * 15;
            let ry = my + 80;
            for (let step = 0; step < 5; step++) {
              const angle = Math.PI/2 + Math.sin(time + i + step) * 0.4 + (i - 3.5) * 0.15;
              const len = 15;
              rx += Math.cos(angle) * len;
              ry += Math.sin(angle) * len;
              ctx.lineTo(rx, ry);
            }
            ctx.stroke();
          }

          // Draw stem (Stipe)
          ctx.fillStyle = '#e2e8f0';
          ctx.beginPath();
          ctx.moveTo(mx - 20, my + 80);
          ctx.quadraticCurveTo(mx - 15, my + 20, mx - 25, my - 20);
          ctx.lineTo(mx + 25, my - 20);
          ctx.quadraticCurveTo(mx + 15, my + 20, mx + 20, my + 80);
          ctx.closePath();
          ctx.fill();

          // Draw gills (Hymenium)
          ctx.fillStyle = '#fda4af';
          ctx.beginPath();
          ctx.ellipse(mx, my - 20, 70, 15, 0, 0, Math.PI * 2);
          ctx.fill();

          // Draw mushroom cap (Pileus)
          ctx.fillStyle = '#ef4444'; // Red cap
          ctx.beginPath();
          ctx.arc(mx, my - 22, 75, Math.PI, 0);
          ctx.closePath();
          ctx.fill();

          // Draw spots on cap
          ctx.fillStyle = '#ffffff';
          const spots = [
            { x: -40, y: -45, r: 8 },
            { x: 40, y: -45, r: 8 },
            { x: 0, y: -65, r: 10 },
            { x: -20, y: -30, r: 6 },
            { x: 20, y: -30, r: 6 },
          ];
          spots.forEach(s => {
            ctx.beginPath();
            ctx.arc(mx + s.x, my - 22 + s.y, s.r, 0, Math.PI * 2);
            ctx.fill();
          });

          // Floating Spores (Particles)
          ctx.fillStyle = '#fef08a'; // Yellow spores
          const wind = params.wind ?? 10; // wind speed
          const releaseRate = params.rate ?? 50; // release rate
          
          for (let i = 0; i < releaseRate; i++) {
            const seed = i * 19.3;
            const t = (Date.now() * 0.001 + seed) % 6; // cycle 6 seconds
            const sx = mx - 50 + (seed % 100) + (t * wind * 2);
            const sy = my - 15 - (t * 25) + Math.sin(t * 3 + seed) * 10;
            
            if (sy < my - 20 && sx > 0 && sx < width) {
              ctx.beginPath();
              ctx.arc(sx, sy, 2 + (i % 2), 0, Math.PI * 2);
              ctx.fill();
            }
          }

          // Hover / Select check
          const m = mouseRef.current;
          let activeLabel = null;
          
          const distToCap = Math.hypot(m.x - mx, m.y - (my - 50));
          if (distToCap < 75 && m.y < my - 20) {
            activeLabel = 'Cap (Pileus)';
          } else if (Math.abs(m.x - mx) < 25 && m.y > my - 20 && m.y < my + 80) {
            activeLabel = 'Stem (Stipe)';
          } else if (Math.hypot(m.x - mx, m.y - (my - 20)) < 70 && m.y >= my - 22 && m.y <= my - 5) {
            activeLabel = 'Gills (Hymenium)';
          } else if (m.y > my + 80) {
            activeLabel = 'Mycelium Network';
          }

          if (m.click) {
            if (activeLabel) {
              setSelectedPart(activeLabel);
            } else {
              setSelectedPart(null);
            }
            m.click = false; // consume click
          }

          const currentPart = selectedPart || activeLabel;
          const currentDesc = currentPart === 'Cap (Pileus)' ? 'The protective top shield of the mushroom. In many species, it features bright warning colors or defensive structures.'
            : currentPart === 'Stem (Stipe)' ? 'Supports the cap and elevates the spore-bearing surface (gills) off the ground to allow wind to carry spores further.'
            : currentPart === 'Gills (Hymenium)' ? 'The ribbed underside where millions of microscopic spores (Basidiospores) are generated and released into the air.'
            : currentPart === 'Mycelium Network' ? 'The actual vegetative body of the fungus, consisting of a vast branching network of thread-like hyphae absorbing nutrients from the soil.'
            : '';

          // Render interactive guide panel on canvas
          ctx.fillStyle = 'rgba(15, 12, 30, 0.85)';
          ctx.strokeStyle = '#4f46e5';
          ctx.lineWidth = 1.5;
          ctx.beginPath();
          ctx.roundRect(15, 15, width - 30, 80, 16);
          ctx.fill();
          ctx.stroke();

          ctx.fillStyle = '#ffffff';
          ctx.font = 'bold 13px sans-serif';
          ctx.fillText(currentPart ? `Interactive Label: ${currentPart}` : '💡 Click/Hover parts of the Fungi to explore functions', 30, 38);
          
          ctx.fillStyle = '#a1a1aa';
          ctx.font = '11px sans-serif';
          const wrappedDesc = currentDesc || 'Explore the vegetative mycelium, supportive stipe, protective pileus, and spore-producing hymenium gills.';
          ctx.fillText(wrappedDesc.slice(0, 95), 30, 58);
          if (wrappedDesc.length > 95) {
            ctx.fillText(wrappedDesc.slice(95), 30, 74);
          }
        }
        else if (lowerSubject.includes('chemistry') || lowerTitle.includes('molecule') || lowerTitle.includes('atom') || lowerTitle.includes('reaction')) {
          // --- CHEMISTRY/ATOM INTERACTIVE BUILDER ---
          const mx = cx;
          const my = cy + 20;
          
          const protons = params.protons ?? 6;
          const electrons = params.electrons ?? 6;
          const energyState = params.energy ?? 1;

          // Draw orbital shells
          ctx.lineWidth = 1.5;
          for (let shell = 1; shell <= 3; shell++) {
            ctx.strokeStyle = shell === energyState ? '#818cf8' : 'rgba(255,255,255,0.06)';
            ctx.beginPath();
            ctx.arc(mx, my, 40 * shell, 0, Math.PI * 2);
            ctx.stroke();
          }

          // Draw nucleus (Protons & Neutrons clustered)
          ctx.shadowBlur = 10;
          ctx.shadowColor = '#f43f5e';
          for (let i = 0; i < protons; i++) {
            const angle = (i * 2 * Math.PI) / protons + (Date.now() * 0.001);
            const radius = 6 + (i % 2) * 3;
            const nx = mx + Math.cos(angle) * radius;
            const ny = my + Math.sin(angle) * radius;
            ctx.fillStyle = i % 2 === 0 ? '#ef4444' : '#3b82f6';
            ctx.beginPath();
            ctx.arc(nx, ny, 6, 0, Math.PI * 2);
            ctx.fill();
          }
          ctx.shadowBlur = 0;

          // Draw orbiting electrons
          const time = Date.now() * 0.0015;
          ctx.fillStyle = '#10b981';
          for (let i = 0; i < electrons; i++) {
            const shellIndex = i < 2 ? 1 : i < 8 ? 2 : 3;
            const shellElecCount = shellIndex === 1 ? 2 : shellIndex === 2 ? 6 : 8;
            const angle = (i * 2 * Math.PI) / shellElecCount + time * (1.5 / shellIndex);
            
            const ex = mx + Math.cos(angle) * (40 * shellIndex);
            const ey = my + Math.sin(angle) * (40 * shellIndex);
            
            ctx.shadowBlur = 8;
            ctx.shadowColor = '#10b981';
            ctx.beginPath();
            ctx.arc(ex, ey, 5, 0, Math.PI * 2);
            ctx.fill();
            ctx.shadowBlur = 0;
          }

          // Interactive feedback
          ctx.fillStyle = 'rgba(15, 12, 30, 0.85)';
          ctx.strokeStyle = '#10b981';
          ctx.lineWidth = 1.5;
          ctx.beginPath();
          ctx.roundRect(15, 15, width - 30, 70, 16);
          ctx.fill();
          ctx.stroke();

          ctx.fillStyle = '#ffffff';
          ctx.font = 'bold 13px sans-serif';
          ctx.fillText(`Interactive Bohr Model • Element: ${protons === 1 ? 'Hydrogen' : protons === 2 ? 'Helium' : protons === 6 ? 'Carbon' : protons === 8 ? 'Oxygen' : 'Custom Isotope'}`, 30, 38);
          
          ctx.fillStyle = '#a1a1aa';
          ctx.font = '11px sans-serif';
          ctx.fillText(`Protons/Neutrons: ${protons} • Electrons: ${electrons} • Shell state: energy shell ${energyState} active`, 30, 58);
        }
        else {
          // --- DEFAULT PHYSICS/CONCEPT PARTICLE MODEL ---
          const gravity = params.gravity ?? 9.8;
          const particlesCount = 25;
          ctx.fillStyle = '#6366f1';
          
          for (let i = 0; i < particlesCount; i++) {
            const seed = i * 23.4;
            const speed = 0.5 + (seed % 3) * 0.3;
            const t = Date.now() * 0.001 * speed;
            const px = ((seed + t * 50) % (width - 60)) + 30;
            const bounceHeight = 80 - (gravity * 3);
            const py = cy + 40 + Math.abs(Math.sin(t + seed)) * -bounceHeight;
            
            ctx.beginPath();
            ctx.arc(px, py, 4 + (i % 4), 0, Math.PI * 2);
            ctx.fill();
          }

          ctx.strokeStyle = '#4338ca';
          ctx.lineWidth = 3;
          ctx.beginPath();
          ctx.moveTo(20, cy + 42);
          ctx.lineTo(width - 20, cy + 42);
          ctx.stroke();

          ctx.fillStyle = 'rgba(15, 12, 30, 0.85)';
          ctx.strokeStyle = '#4f46e5';
          ctx.lineWidth = 1.5;
          ctx.beginPath();
          ctx.roundRect(15, 15, width - 30, 70, 16);
          ctx.fill();
          ctx.stroke();

          ctx.fillStyle = '#ffffff';
          ctx.font = 'bold 13px sans-serif';
          ctx.fillText('Interactive 2D Particle Kinetics Simulator', 30, 38);
          ctx.fillStyle = '#a1a1aa';
          ctx.font = '11px sans-serif';
          ctx.fillText(`Adjust slider controls to modify local gravitational pull (${gravity} m/s²).`, 30, 58);
        }
      }

      animationRef.current = requestAnimationFrame(render);
    };

    render();

    const handleCanvasClick = (e: MouseEvent) => {
      if (type === 'projectile_motion') {
        const rect = canvas.getBoundingClientRect();
        const clickX = e.clientX - rect.left;
        const clickY = e.clientY - rect.top;
        if (clickX >= width - 120 && clickX <= width - 20 && clickY >= 20 && clickY <= 50) {
          const angleRad = ((params.angle || 45) * Math.PI) / 180;
          const speed = params.speed || 20;
          projectileStateRef.current = {
            x: 20,
            y: height - 40,
            vx: speed * Math.cos(angleRad) * 4,
            vy: -speed * Math.sin(angleRad) * 4,
            t: 0,
            path: [],
          };
        }
      }
    };
    canvas.addEventListener('click', handleCanvasClick);

    return () => {
      if (animationRef.current) cancelAnimationFrame(animationRef.current);
      resizeObserver.disconnect();
      if (canvas) canvas.removeEventListener('click', handleCanvasClick);
    };
  }, [three_js_config, params]);

  const handleSliderChange = (key: string, val: number) => {
    setParams((prev) => ({ ...prev, [key]: val }));
  };

  const isSketchfab = !!sketchfab_hint;

  return (
    <div className="w-full h-full flex flex-col bg-zinc-950/60 rounded-xl border border-zinc-800 overflow-hidden backdrop-blur-md">
      {/* Dynamic Lab Guide Description */}
      {three_js_config?.description && (
        <div className="p-3.5 bg-indigo-950/20 border-b border-zinc-800 text-xs text-zinc-300">
          <strong>🔬 Lab Guide: </strong> {three_js_config.description}
        </div>
      )}

      <div className="flex-1 min-h-[300px] relative">
        {/* Switch button overlay for Sketchfab models */}
        {isSketchfab && (
          <div className="absolute top-3 left-3 z-20">
            <button
              type="button"
              onClick={() => setShow2DInterpretation(!show2DInterpretation)}
              className="px-3.5 py-2 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white rounded-xl text-[10px] font-black uppercase tracking-wider transition-all shadow-lg shadow-black/50 active:scale-95 border border-indigo-400/20"
            >
              {show2DInterpretation ? "🔬 Switch to 3D View" : "🎨 Switch to Interactive 2D Simulation"}
            </button>
          </div>
        )}

        {isSketchfab && !show2DInterpretation ? (
          <div className="w-full h-full relative">
            {sketchfabLoading && (
              <div className="absolute inset-0 flex flex-col items-center justify-center bg-zinc-950 z-10">
                <div className="w-12 h-12 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin"></div>
                <p className="mt-4 text-zinc-400 text-sm">Loading 3D Model from Sketchfab...</p>
              </div>
            )}
            <iframe
              src={`https://sketchfab.com/models/${activeModelId}/embed?autostart=1&ui_theme=dark&preload=1`}
              title="3D Model Viewer"
              className="w-full h-full border-none"
              onLoad={() => setSketchfabLoading(false)}
              allow="autoplay; fullscreen; xr-spatial-tracking"
            />
          </div>
        ) : (three_js_config || show2DInterpretation) ? (
          <canvas ref={canvasRef} className="w-full h-full block cursor-pointer" />
        ) : (
          <div className="w-full h-full flex flex-col items-center justify-center bg-zinc-950/80">
            <div className="relative w-16 h-16">
              <div className="absolute inset-0 border-2 border-indigo-500/20 rounded-lg"></div>
              <div className="absolute inset-0 border-2 border-t-indigo-500 rounded-lg animate-spin"></div>
            </div>
            <p className="mt-4 text-zinc-400 text-sm font-medium">Virtual 3D Model Loading...</p>
          </div>
        )}
      </div>

      {/* Control sliders */}
      {(three_js_config || show2DInterpretation) && (
        <div className="p-4 bg-zinc-900/80 border-t border-zinc-800 flex flex-col gap-3">
          {/* 1. Dynamic Sliders from config */}
          {three_js_config?.controls && three_js_config.controls.map((control) => {
            const val = params[control.name] ?? control.defaultValue;
            return (
              <div key={control.name} className="flex flex-col gap-1">
                <div className="flex justify-between text-xs font-semibold text-zinc-400">
                  <span>{control.label}</span>
                  <span className="text-indigo-400 font-mono">
                    {val.toFixed(1)} {control.unit || ''}
                  </span>
                </div>
                <input
                  type="range"
                  min={control.min}
                  max={control.max}
                  step={control.step}
                  value={val}
                  onChange={(e) => handleSliderChange(control.name, parseFloat(e.target.value))}
                  className="w-full h-1.5 bg-zinc-700 rounded-lg appearance-none cursor-pointer accent-indigo-500"
                />
              </div>
            );
          })}

          {/* 2. Legacy fallback sliders */}
          {three_js_config && !three_js_config.controls && three_js_config.sliders && three_js_config.sliders.map((sliderKey) => {
            let min = 0;
            let max = 100;
            let step = 1;
            let label = sliderKey;

            if (sliderKey === 'a') { min = -5; max = 5; step = 0.1; label = 'Curvature (a)' }
            else if (sliderKey === 'b') { min = -10; max = 10; step = 0.5; label = 'Slope offset (b)' }
            else if (sliderKey === 'c') { min = -10; max = 10; step = 0.5; label = 'Y-Intercept (c)' }
            else if (sliderKey === 'm') { min = -5; max = 5; step = 0.1; label = 'Slope (m)' }
            else if (sliderKey === 'amplitude') { min = 0.5; max = 4; step = 0.1; label = 'Amplitude (A)' }
            else if (sliderKey === 'frequency') { min = 0.2; max = 5; step = 0.1; label = 'Frequency (f)' }
            else if (sliderKey === 'mean') { min = -5; max = 5; step = 0.1; label = 'Mean (μ)' }
            else if (sliderKey === 'std') { min = 0.2; max = 3; step = 0.1; label = 'Standard Deviation (σ)' }
            else if (sliderKey === 'angle') { min = 10; max = 80; step = 1; label = 'Launch Angle (θ)' }
            else if (sliderKey === 'speed') { min = 5; max = 45; step = 1; label = 'Initial Speed (v)' }
            else if (sliderKey === 'gravity') { min = 2; max = 25; step = 0.2; label = 'Gravity (g)' }
            else if (sliderKey === 'voltage') { min = 2; max = 24; step = 1; label = 'Voltage (V)' }
            else if (sliderKey === 'resistance') { min = 1; max = 20; step = 0.5; label = 'Resistance (R)' }
            else if (sliderKey === 'pour') { min = 0; max = 100; step = 1; label = 'Pour Amount (%)' }
            else if (sliderKey === 'temperature') { min = 0; max = 100; step = 1; label = 'Reaction Temp (°C)' }

            const val = params[sliderKey] ?? 0;

            return (
              <div key={sliderKey} className="flex flex-col gap-1">
                <div className="flex justify-between text-xs font-semibold text-zinc-400">
                  <span>{label}</span>
                  <span className="text-indigo-400 font-mono">{val.toFixed(1)}</span>
                </div>
                <input
                  type="range"
                  min={min}
                  max={max}
                  step={step}
                  value={val}
                  onChange={(e) => handleSliderChange(sliderKey, parseFloat(e.target.value))}
                  className="w-full h-1.5 bg-zinc-700 rounded-lg appearance-none cursor-pointer accent-indigo-500"
                />
              </div>
            );
          })}

          {/* 3. Custom interactive 2D Simulation sliders (when no config) */}
          {!three_js_config && show2DInterpretation && (() => {
            const lowerSubject = _subject.toLowerCase();
            const lowerTitle = (sketchfab_hint || '').toLowerCase();
            const isFungi = lowerSubject.includes('biology') || lowerSubject.includes('fungi') || lowerTitle.includes('fungi') || lowerTitle.includes('mushroom');
            const isChem = lowerSubject.includes('chemistry') || lowerTitle.includes('molecule') || lowerTitle.includes('atom');

            if (isFungi) {
              const rateVal = params.rate ?? 50;
              const windVal = params.wind ?? 10;
              return (
                <>
                  <div className="flex flex-col gap-1">
                    <div className="flex justify-between text-xs font-semibold text-zinc-400">
                      <span>Spore Release Rate</span>
                      <span className="text-indigo-400 font-mono">{rateVal.toFixed(0)}</span>
                    </div>
                    <input type="range" min="10" max="100" step="5" value={rateVal} onChange={e => handleSliderChange('rate', parseFloat(e.target.value))}
                      className="w-full h-1.5 bg-zinc-700 rounded-lg appearance-none cursor-pointer accent-indigo-500" />
                  </div>
                  <div className="flex flex-col gap-1">
                    <div className="flex justify-between text-xs font-semibold text-zinc-400">
                      <span>Wind Velocity</span>
                      <span className="text-indigo-400 font-mono">{windVal.toFixed(0)} m/s</span>
                    </div>
                    <input type="range" min="0" max="40" step="2" value={windVal} onChange={e => handleSliderChange('wind', parseFloat(e.target.value))}
                      className="w-full h-1.5 bg-zinc-700 rounded-lg appearance-none cursor-pointer accent-indigo-500" />
                  </div>
                </>
              );
            }
            if (isChem) {
              const protVal = params.protons ?? 6;
              const elecVal = params.electrons ?? 6;
              const energyVal = params.energy ?? 1;
              return (
                <>
                  <div className="flex flex-col gap-1">
                    <div className="flex justify-between text-xs font-semibold text-zinc-400">
                      <span>Protons / Neutrons</span>
                      <span className="text-indigo-400 font-mono">{protVal.toFixed(0)}</span>
                    </div>
                    <input type="range" min="1" max="10" step="1" value={protVal} onChange={e => handleSliderChange('protons', parseFloat(e.target.value))}
                      className="w-full h-1.5 bg-zinc-700 rounded-lg appearance-none cursor-pointer accent-indigo-500" />
                  </div>
                  <div className="flex flex-col gap-1">
                    <div className="flex justify-between text-xs font-semibold text-zinc-400">
                      <span>Electrons Count</span>
                      <span className="text-indigo-400 font-mono">{elecVal.toFixed(0)}</span>
                    </div>
                    <input type="range" min="1" max="10" step="1" value={elecVal} onChange={e => handleSliderChange('electrons', parseFloat(e.target.value))}
                      className="w-full h-1.5 bg-zinc-700 rounded-lg appearance-none cursor-pointer accent-indigo-500" />
                  </div>
                  <div className="flex flex-col gap-1">
                    <div className="flex justify-between text-xs font-semibold text-zinc-400">
                      <span>Excitation Level</span>
                      <span className="text-indigo-400 font-mono">Shell {energyVal.toFixed(0)}</span>
                    </div>
                    <input type="range" min="1" max="3" step="1" value={energyVal} onChange={e => handleSliderChange('energy', parseFloat(e.target.value))}
                      className="w-full h-1.5 bg-zinc-700 rounded-lg appearance-none cursor-pointer accent-indigo-500" />
                  </div>
                </>
              );
            }
            const gravVal = params.gravity ?? 9.8;
            return (
              <div className="flex flex-col gap-1">
                <div className="flex justify-between text-xs font-semibold text-zinc-400">
                  <span>Gravitational Acceleration</span>
                  <span className="text-indigo-400 font-mono">{gravVal.toFixed(1)} m/s²</span>
                </div>
                <input type="range" min="1" max="25" step="0.5" value={gravVal} onChange={e => handleSliderChange('gravity', parseFloat(e.target.value))}
                  className="w-full h-1.5 bg-zinc-700 rounded-lg appearance-none cursor-pointer accent-indigo-500" />
              </div>
            );
          })()}
        </div>
      )}
    </div>
  );
};
