#!/bin/bash
# ============================================================
# 🚀 AUTO SETUP SCRIPT — ecommerce website
# Generated by Universal AI Build Engine
# ============================================================

echo "🔧 Setting up ecommerce website..."
echo ""

# Step 1: Backend Setup
echo "📦 Installing Backend dependencies..."
cd backend
npm install
cd ..
echo "✅ Backend installed"
echo ""

# Step 2: Admin Panel Setup
echo "🎛️ Installing Admin Panel dependencies..."
cd admin
npm install
cd ..
echo "✅ Admin installed"
echo ""

# Step 3: Frontend Setup
echo "🎨 Installing Frontend dependencies..."
cd frontend
npm install
cd ..
echo "✅ Frontend installed"
echo ""

# Step 4: Database
echo "📌 Database Setup:"
echo "# Ensure your SQL database server is running"
echo ""

# Step 5: Environment
echo "⚙️ IMPORTANT: Configure .env files before starting!"
echo "  backend/.env → MONGO_URI / DB_URI, JWT_SECRET, PORT=5000"
echo ""

echo "=========================================="
echo "🟢 Start Guide:"
echo "  Terminal 1 → cd backend && npm run dev"
echo "  Terminal 2 → cd admin && npm run dev   (Admin: http://localhost:3001)"
echo "  Terminal 3 → cd frontend && npm run dev (App: http://localhost:3000)"
echo "=========================================="
echo ""
echo "✅ ecommerce website is ready to use!"
