import os
import zipfile
import shutil
import json
import logging
import re
from datetime import datetime
from docx import Document
from docx.shared import Pt, Inches
from pptx import Presentation
from pptx.util import Inches as PptInches, Pt as PptPt
from fpdf import FPDF
from ml.academic_brain import academic_brain
from ml.content_forge import content_forge
from rich.console import Console

logger = logging.getLogger(__name__)
console = Console()

def sanitize_for_xml(text):
    """Removes control characters that break XML-based formats (DOCX/PPTX)."""
    if not text: return ""
    # Remove illegal XML characters
    # Ref: https://stackoverflow.com/questions/1707890/fastway-to-remove-illegal-xml-unicode-characters-from-python-unicode-string
    illegal_chars = re.compile(r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x84\x86-\x9f\ud800-\udfff\ufdd0-\ufdef\ufffe\uffff]')
    return illegal_chars.sub('', str(text))

def run(config, prompt_data):
    """
    GENESIS UNIVERSAL ARCHITECT PIPELINE (TITAN SUPREME).
    Architects & Builds End-to-End Projects with 22-point fidelity.
    Generates: DOCX, PDF, PPT, and Source Code.
    """
    metadata = config.get("metadata", config)
    blueprint = metadata.get("blueprint", {})
    project_id = metadata.get("projectId", "p_" + datetime.now().strftime("%H%M%S"))
    
    tier = blueprint.get("tier", "BACHELOR")
    vision_title = sanitize_for_xml(blueprint.get("title", "Industrial Academic Project"))
    points = blueprint.get("points22", {})
    code_assets = blueprint.get("codeSnippets", [])
    viva_questions = blueprint.get("vivaQuestions", [])

    console.print(f"[bold gold1]🏗️ GENESIS ARCHITECT ACTIVE: {vision_title} ({tier})[/bold gold1]")

    # 1. SETUP DIRECTORY STRUCTURE
    base_storage = "storage/projects"
    project_dir = os.path.join(base_storage, project_id)
    os.makedirs(project_dir, exist_ok=True)
    
    tier_key = tier.upper() if tier else "BACHELOR"
    template_path = os.path.join("storage", "templates", tier_key)
    blueprint_file = os.path.join(template_path, "blueprint.json")
    
    master_blueprint = {}
    if os.path.exists(blueprint_file):
        with open(blueprint_file, "r") as f:
            master_blueprint = json.load(f)
    
    dirs = ["DOCS", "PPT", "SOURCE_CODE", "VIVA_PREP"]
    for d in dirs:
        os.makedirs(os.path.join(project_dir, d), exist_ok=True)
    
    # 2. GENERATE SOURCE CODE ASSETS
    src_dir = os.path.join(project_dir, "SOURCE_CODE")
    for snippet in code_assets:
        # Strip leading slashes to prevent absolute path escapes on Windows
        clean_name = snippet.get("file", "app.py").lstrip("/").lstrip("\\")
        file_path = os.path.normpath(os.path.join(src_dir, clean_name))
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(snippet.get("content", ""))
        except: pass

    # 3. GENERATE PROFESSIONAL DOCX
    doc = Document()
    doc.add_heading(vision_title, 0).alignment = 1
    field_text = sanitize_for_xml(metadata.get('field', 'Industrial Technical'))
    doc.add_paragraph(f"Academic & Industrial Project Blueprint\nField: {field_text}\n{tier_key} Tier Execution Protocol\nGenerated by FutureBRTS Genesis Architect").alignment = 1
    doc.add_page_break()

    sections_to_render = master_blueprint.get("structure", [])
    if not sections_to_render:
        for i in range(1, 23):
            key = f"point_{i}_"
            actual_key = next((k for k in points.keys() if k.startswith(key)), None)
            title = actual_key.split('_', 2)[-1].replace("_", " ").title() if actual_key else f"Section {i}"
            sections_to_render.append({"text": title, "metadata_key": actual_key or key})

    doc.add_heading("Table of Contents", level=1)
    for i, s in enumerate(sections_to_render, 1):
        doc.add_paragraph(f"{i}. {sanitize_for_xml(s['text'])}")
    doc.add_page_break()

    for i, section in enumerate(sections_to_render, 1):
        title = sanitize_for_xml(section["text"])
        actual_key = next((k for k in points.keys() if k.startswith(section.get("metadata_key", f"point_{i}_"))), None)
        content = sanitize_for_xml(points.get(actual_key, "Details pending."))
        
        doc.add_heading(f"{i}. {title}", level=1)
        doc.add_paragraph(content)

    doc_filename = f"Technical_Report_{project_id}.docx"
    doc_path = os.path.join(project_dir, "DOCS", doc_filename)
    doc.save(doc_path)

    # 4. GENERATE A4 PDF
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt=vision_title, ln=True, align='C')
    pdf.ln(10)
    
    for i, section in enumerate(sections_to_render, 1):
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, f"{i}. {sanitize_for_xml(section['text'])}", ln=True)
        pdf.set_font("Arial", size=10)
        actual_key = next((k for k in points.keys() if k.startswith(section.get('metadata_key', f"point_{i}_"))), None)
        pdf.multi_cell(0, 5, sanitize_for_xml(points.get(actual_key, "Synthesis pending.")))
        pdf.ln(5)
    
    pdf_filename = f"Industrial_PDF_{project_id}.pdf"
    pdf_path = os.path.join(project_dir, "DOCS", pdf_filename)
    pdf.output(pdf_path, 'F')

    # 5. GENERATE PPT
    prs = Presentation()
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = vision_title
    slide.placeholders[1].text = f"Field: {field_text}\n{tier_key} Level Blueprint"

    for i in range(0, min(len(sections_to_render), 10), 2):
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        s1 = sections_to_render[i]
        slide.shapes.title.text = sanitize_for_xml(s1["text"])
        c1 = sanitize_for_xml(points.get(next((k for k in points.keys() if k.startswith(s1.get('metadata_key', ''))), None), "Details in DOCS"))
        slide.placeholders[1].text = f"• {sanitize_for_xml(s1['text'])}:\n{str(c1)[:300]}..."

    ppt_filename = f"Presentation_{project_id}.pptx"
    ppt_path = os.path.join(project_dir, "PPT", ppt_filename)
    prs.save(ppt_path)

    # 6. VIVA IQ BANK
    viva_dir = os.path.join(project_dir, "VIVA_PREP")
    os.makedirs(viva_dir, exist_ok=True)
    viva_path = os.path.join(viva_dir, "Viva_Intelligence.txt")
    with open(viva_path, "w", encoding="utf-8") as f:
        f.write(f"VIVA PREPARATION GUIDE - {vision_title}\n\n")
        for q in (viva_questions or []):
            f.write(f"Q: {sanitize_for_xml(q.get('question', ''))}\nA: {sanitize_for_xml(q.get('answer', ''))}\n\n")

    # 7. PACKAGING & PERSISTENCE
    final_doc_path = os.path.join(base_storage, doc_filename)
    final_pdf_path = os.path.join(base_storage, pdf_filename)
    final_ppt_path = os.path.join(base_storage, ppt_filename)
    
    shutil.copy2(doc_path, final_doc_path)
    shutil.copy2(pdf_path, final_pdf_path)
    shutil.copy2(ppt_path, final_ppt_path)

    zip_filename = f"{project_id}_TITAN_{tier_key}_PACKAGE.zip"
    zip_path = os.path.join(base_storage, zip_filename)
    
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, _, files in os.walk(project_dir):
            for file in files:
                abs_f = os.path.join(root, file)
                rel_f = os.path.relpath(abs_f, project_dir).replace('\\', '/')
                zipf.write(abs_f, rel_f)

    # Cleanup temp folder safely
    try:
        shutil.rmtree(project_dir)
    except: pass

    worker_url = os.getenv("WORKER_PUBLIC_URL", "http://localhost:8000")
    
    return {
        "status": "completed",
        "result": {
            "vision": vision_title,
            "artifacts": {
                # Nested for Builder
                "zip": {"url": f"{worker_url}/downloads/{zip_filename}"},
                "word": {"url": f"{worker_url}/downloads/{doc_filename}"},
                "pdf": {"url": f"{worker_url}/downloads/{pdf_filename}"},
                "ppt": {"url": f"{worker_url}/downloads/{ppt_filename}"},
                # Flat for Projects Registry
                "zipUrl": f"{worker_url}/downloads/{zip_filename}",
                "documentUrl": f"{worker_url}/downloads/{doc_filename}",
                "vivaQuestions": viva_questions
            },
            "tier": tier_key,
            "degree": field_text,
            "domain": metadata.get("subCategory", "General")
        }
    }
