import os
import json
import time
from docx import Document
from fpdf import FPDF
from pptx import Presentation
from docx.shared import Pt, Inches
from core.cortex import intelligence
from utils.sanitizer import sanitize_for_xml
from utils.diagram_engine import diagram_engine
from utils.reporter import reporter

def run(config, prompt_data):
    """
    TITAN DEEP DOCUMENTATION PIPELINE
    Iterative batch writing for 22 points with Neural Diagram Synthesis.
    """
    project_id = config.get("projectId", "temp_titan")
    blueprint = config.get("blueprint", {})
    tier = config.get("tier", "BACHELOR")
    
    reporter.log(project_id, "🚀 Initiating Titan Deep Documentation Engine...", status="DOCUMENTING", current_step="Neural Architect Mapping")
    
    # 1. SETUP WORKSPACE
    storage_dir = os.path.join("storage", "projects", project_id)
    os.makedirs(storage_dir, exist_ok=True)
    os.makedirs(os.path.join(storage_dir, "DOCS"), exist_ok=True)
    os.makedirs(os.path.join(storage_dir, "ASSETS"), exist_ok=True)
    
    print(f"🏗️ TITAN DEEP DOCS: Initiating for {project_id} | Tier: {tier}")
    
    # 2. BATCH CHUNKING LOGIC
    chunks = [
        ["p1_abstract", "p2_intro", "p3_scope", "p4_stack", "p5_existing"],
        ["p6_proposed", "p7_pros_cons", "p8_feasibility", "p9_dfd", "p10_erd"],
        ["p11_std", "p12_data_dict", "p13_schema", "p14_arch", "p15_uml"],
        ["p16_ui", "p17_strategy", "p18_testing", "p19_security", "p20_conclusion", "p21_biblio", "p22_viva"]
    ]
    
    final_content = {}
    diagrams = {}
    context_buffer = f"Project: {blueprint.get('title')}\nVision: {blueprint.get('vision')}\nStack: {json.dumps(blueprint.get('stack'))}\n"
    
    for i, chunk in enumerate(chunks, 1):
        print(f"📝 Writing Chunk {i}/4...")
        reporter.log(project_id, f"📝 Synthesizing Documentation Chunk {i}/4 ({', '.join(chunk)})...")
        
        chunk_keys = ", ".join(chunk)
        chunk_intent = {k: blueprint.get("outline22", {}).get(k, "General academic detail") for k in chunk}
        
        prompt = f"""
        YOU ARE A PROJECT ARCHITECT (Tier: {tier}).
        Deeply write the following sections based on the Strategic Intent:
        {json.dumps(chunk_intent, indent=2)}
        
        [CONTEXT FROM PREVIOUS STAGES]
        {context_buffer}
        
        [RULES]
        1. Use industrial terminology.
        2. Minimum 500 words PER POINT.
        3. For PhD/Master, include research gaps and comparative analysis.
        4. IF A SECTION IS p9_dfd, p10_erd, p13_schema, or p14_arch, PROVIDE A CLEAN MERMAID.JS CODE block labeled with [MERMAID_START] and [MERMAID_END].
        5. Return as JSON: {{ "point_key": "Full detailed content..." }}
        """
        
        response = intelligence.think(prompt, json_mode=True)
        try:
            chunk_data = json.loads(response) if isinstance(response, str) else response
            for k, v in chunk_data.items():
                # Extract Mermaid blocks if present
                if "[MERMAID_START]" in str(v):
                    m_start = v.find("[MERMAID_START]") + 15
                    m_end = v.find("[MERMAID_END]")
                    if m_end > m_start:
                        mermaid_code = v[m_start:m_end].strip()
                        print(f"🎨 Rendering Diagram for {k}...")
                        reporter.log(project_id, f"🎨 Rendering Industrial Diagram for {k}...")
                        img_path = diagram_engine.render_mermaid(mermaid_code, output_dir=os.path.join(storage_dir, "ASSETS"))
                        if img_path:
                            diagrams[k] = img_path
                        # Clean the text from tag blocks
                        v = v.replace(f"[MERMAID_START]{mermaid_code}[MERMAID_END]", "").strip()
                
                final_content[k] = v
                
            context_buffer += f"\nSummarized {chunk_keys} for continuity."
        except Exception as e:
            print(f"⚠️ Chunk {i} parsing failed: {e}")
            for k in chunk: final_content[k] = f"Detailed analysis for {k} pending neural polish."

    # 3. FINAL ASSEMBLY (WORD - ACADEMIC STYLE)
    doc_path = os.path.join(storage_dir, "DOCS", f"Technical_Report_{project_id}.docx")
    doc = Document()
    
    # --- ACADEMIC STYLING ---
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Times New Roman'
    font.size = Pt(12)
    
    # --- FRONT PAGE ---
    doc.add_heading(blueprint.get('title', 'Titan Project').upper(), 0).alignment = 1
    doc.add_paragraph("\n" * 5)
    doc.add_heading(f"A Technical Deep-Dive & Industrial Blueprint", level=1).alignment = 1
    doc.add_paragraph("\n" * 2)
    p = doc.add_paragraph()
    p.alignment = 1
    r = p.add_run(f"Project Tier: {tier}\nExecution Protocol: Genesis v2.2\n")
    r.bold = True
    doc.add_paragraph("\n" * 8)
    doc.add_paragraph(f"Generated by FutureBRTS Titan Architect Network\nDate: {time.strftime('%Y-%m-%d')}").alignment = 1
    doc.add_page_break()
    
    # --- TABLE OF CONTENTS (Static for now, as python-docx TOC is tricky) ---
    doc.add_heading("Table of Contents", level=1)
    for k in [p for sub in chunks for p in sub]:
        clean_title = k.replace("p", "").replace("_", " ").title().strip()
        doc.add_paragraph(clean_title)
    doc.add_page_break()
    
    # --- CONTENT RENDERING ---
    for k in [p for sub in chunks for p in sub]:
        if k not in final_content: continue
        v = final_content[k]
        
        # Clean title (e.g., p1_abstract -> Abstract)
        clean_title = k.split("_", 1)[1].replace("_", " ").title() if "_" in k else k
        
        heading = doc.add_heading(clean_title, level=1)
        heading.style.font.name = 'Times New Roman'
        heading.style.font.size = Pt(16)
        
        # If there's a diagram, add it after the heading
        if k in diagrams:
            try:
                doc.add_picture(diagrams[k], width=Inches(6))
                doc.add_paragraph(f"Figure: Industrial {clean_title} Schematic").alignment = 1
            except Exception as diagram_err:
                print(f"Diagram error for {k}: {diagram_err}")
                doc.add_paragraph("[Visual Interface Synchronized - Logic Artifact Linked]")
        
        # Section Content
        para = doc.add_paragraph()
        para_run = para.add_run(sanitize_for_xml(str(v)))
        para.alignment = 3 # Justified
        
        doc.add_page_break()
    
    doc.save(doc_path)

    return {
        "status": "completed",
        "result": {
            "project_id": project_id,
            "doc_path": doc_path,
            "artifacts": {
                "docUrl": f"/download/projects/{project_id}/DOCS/Technical_Report_{project_id}.docx"
            }
        }
    }
