import { FileText, Scale, ShieldAlert, Gavel, Cpu, Key, Activity, RefreshCcw, ArrowRight, BookOpen, Lock, Terminal, ShieldCheck, Database } from "lucide-react"
import { motion, useScroll, useTransform } from "framer-motion"
import { Button } from "@/components/ui/Button"

export default function Terms() {
    const { scrollYProgress } = useScroll();
    const rotateValue = useTransform(scrollYProgress, [0, 1], [0, 180]);

    return (
        <div className="pt-24 pb-16 px-6 max-w-7xl mx-auto space-y-16 md:space-y-20 text-white font-sans overflow-x-hidden relative">

            {/* --- SECTION 1: THE LEGAL HERO --- */}
            <section className="relative flex flex-col items-center text-center space-y-12">
                <motion.div
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    className="relative"
                >
                    {/* Rotating Circular HUD Background */}
                    <motion.div
                        style={{ rotate: rotateValue }}
                        className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] border border-dashed border-amber-500/10 rounded-full -z-10"
                    />
                    <motion.div
                        style={{ rotate: rotateValue }}
                        className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[350px] h-[350px] border border-orange-500/10 rounded-full -z-10"
                    />

                    <div className="space-y-6 relative z-10">
                        <div className="inline-flex items-center gap-2.5 px-6 py-2 rounded-full bg-amber-500/5 border border-amber-500/10 backdrop-blur-xl text-[10px] font-black uppercase tracking-[0.5em] text-amber-400">
                            <Gavel size={12} className="animate-pulse" /> LEGAL_HANDSHAKE_INITIATED
                        </div>
                        <h1 className="text-3xl md:text-5xl font-black tracking-tighter leading-none mb-8 uppercase italic">
                            BUILDER <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-400 via-orange-500 to-amber-700 animate-gradient-x drop-shadow-[0_0_20px_rgba(245,158,11,0.3)]">AGREEMENT.</span>
                        </h1>
                    </div>
                </motion.div>

                <p className="text-sm md:text-base text-gray-500 font-medium leading-relaxed max-w-4xl mx-auto border-y border-white/5 py-8 px-6 italic text-center">
                    "By accessing the FutureBuilder Industrial Engine, you enter a binding <span className="text-white font-black underline decoration-amber-500 decoration-2 underline-offset-8">Execution Protocol</span>. We provide the tools; you provide the integrity."
                </p>
                
                <div className="flex gap-4">
                    <div className="flex items-center gap-2 px-4 py-2 bg-white/5 rounded-xl border border-white/10 text-[9px] font-black uppercase tracking-widest text-amber-400">
                        <Scale size={12} /> BINDING_CONTRACT
                    </div>
                    <div className="flex items-center gap-2 px-4 py-2 bg-white/5 rounded-xl border border-white/10 text-[9px] font-black uppercase tracking-widest text-orange-400">
                        <Terminal size={12} /> API_USAGE_POLICY
                    </div>
                </div>
            </section>

            {/* --- SECTION 2: THE TERMS MATRIX --- */}
            <section className="space-y-12">
                <div className="text-center space-y-3">
                    <span className="text-[10px] font-black uppercase tracking-[0.4em] text-gray-600">The parameters of operation</span>
                    <h2 className="text-2xl md:text-3xl font-black tracking-tighter italic uppercase text-white leading-none">CORE_RULES.</h2>
                </div>

                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                    <TermsCard 
                        icon={<Key />}
                        title="ACCOUNT_SECURITY"
                        desc="You are the sole operator of your credentials. Sharing your neural link leads to immediate termination of service."
                        id="01"
                        color="amber"
                    />
                    <TermsCard 
                        icon={<Cpu />}
                        title="AI_COGNITIVE_LIMIT"
                        desc="All roadmaps and curricula are statistical predictions generated by neural models. Provided 'AS IS'. No guarantees on placements, grades, or career success."
                        id="02"
                        color="orange"
                        active
                    />
                    <TermsCard 
                        icon={<ShieldAlert />}
                        title="PROHIBITED_ACTS"
                        desc="Reverse engineering our neural logic, cloning system agents, or using the engine for unauthorized scraping is strictly forbidden."
                        id="03"
                        color="amber"
                    />
                </div>
            </section>

            {/* --- SECTION 3: DATA & AI PROCESSING PROTOCOL (Strict Liability Shield) --- */}
            <section className="bg-[#020204]/90 border border-white/5 rounded-[2rem] md:rounded-[3rem] p-6 md:p-12 relative overflow-hidden group shadow-[inset_0_0_30px_rgba(245,158,11,0.02)]">
                <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-amber-500/5 blur-[120px] -z-10 group-hover:opacity-100 transition-opacity duration-1000" />

                <div className="grid lg:grid-cols-2 gap-12 items-center relative z-10">
                    <div className="space-y-8 text-left">
                        <div className="space-y-4 text-left">
                            <span className="text-[10px] font-black uppercase tracking-[0.4em] text-amber-500">// INTEGRITY_LAYER</span>
                            <h2 className="text-2xl md:text-4xl font-black tracking-tighter italic uppercase text-white leading-none">DATA_&_AI_SAFETY.</h2>
                            <div className="h-1 w-20 bg-amber-500" />
                            <p className="text-sm md:text-base text-gray-500 font-medium leading-relaxed">
                                We enforce strict legal buffers to protect the integrity of our engines. By initializing this dashboard, you bind yourself to the following protocols:
                            </p>
                        </div>

                        <div className="grid gap-6">
                            <div className="space-y-1.5 pl-4 border-l-2 border-amber-500/20">
                                <h4 className="text-sm font-black italic uppercase text-white tracking-tighter text-left">
                                    <Cpu size={14} className="text-amber-500 inline-block mr-2 align-text-bottom" /> AI GENERATION MATRIX
                                </h4>
                                <p className="text-xs text-gray-500 leading-relaxed">
                                    Our platform acts as a predictive learning facilitator. Curriculums, assessments, and roadmap logic are generated via LLM integrations (Groq, OpenAI) using heuristic evaluations. The platform makes no warranties regarding the correctness, completeness, or industry viability of the generated data.
                                </p>
                            </div>
                            <div className="space-y-1.5 pl-4 border-l-2 border-amber-500/20">
                                <h4 className="text-sm font-black italic uppercase text-white tracking-tighter text-left">
                                    <Database size={14} className="text-amber-500 inline-block mr-2 align-text-bottom" /> DATA RETENTION & ENCRYPTION
                                </h4>
                                <p className="text-xs text-gray-500 leading-relaxed">
                                    Your uploaded resumes, profile attributes, and progress tokens are encrypted at rest (AES-256) and in transit (SSL/TLS). We process data to optimize skill-gap identification and predictive matching algorithms. Data is purged within 30 days of account termination requests.
                                </p>
                            </div>
                            <div className="space-y-1.5 pl-4 border-l-2 border-amber-500/20">
                                <h4 className="text-sm font-black italic uppercase text-white tracking-tighter text-left">
                                    <ShieldCheck size={14} className="text-amber-500 inline-block mr-2 align-text-bottom" /> CLASS ACTION & LIABILITY WAIVER
                                </h4>
                                <p className="text-xs text-gray-500 leading-relaxed">
                                    Users, students, and institutional builders agree that under no circumstances shall FutureBRTS, Mayur Savaliya, or any of its contributors be liable for any direct or indirect damages, career setbacks, financial losses, or failures. By proceeding, you waive any right to file claims, legal cases, or participate in class-action lawsuits against the platform.
                                </p>
                            </div>
                        </div>
                    </div>

                    <div className="relative">
                        <div className="p-1 rounded-[2.5rem] bg-gradient-to-br from-amber-500/20 via-white/5 to-orange-500/20 shadow-2xl">
                            <div className="bg-[#050508] rounded-[2rem] p-8 md:p-10 flex flex-col items-center justify-center text-center space-y-6 border border-white/5">
                                <motion.div
                                    animate={{ scale: [1, 1.05, 1], rotate: [0, 2, -2, 0] }}
                                    transition={{ duration: 6, repeat: Infinity }}
                                >
                                    <FileText size={72} className="text-amber-500/30" />
                                </motion.div>
                                <div className="space-y-1">
                                    <h3 className="text-lg font-black italic tracking-tighter uppercase">BINDING_SIGNATURE</h3>
                                    <p className="text-[9px] text-amber-400 font-black tracking-[0.4em] uppercase font-mono">Status: Legally Enforced v9.4</p>
                                </div>
                                <Button className="w-full h-14 bg-amber-500 text-white font-[1000] uppercase tracking-[0.2em] text-[10px] rounded-xl hover:bg-amber-400 hover:shadow-[0_0_30px_rgba(245,158,11,0.3)] transition-all border-none">
                                    VIEW_FULL_LEGAL_PACKET
                                </Button>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* --- SECTION 4: TERMINATION & EXIT LOGIC --- */}
            <section className="space-y-8">
                <div className="text-center space-y-4">
                    <div className="inline-flex items-center gap-2.5 px-6 py-2 rounded-full bg-white/5 border border-white/10 text-[10px] font-black uppercase tracking-[0.4em] text-gray-500 font-mono">
                        <RefreshCcw size={12} className="hover:rotate-180 transition-transform duration-700 text-amber-500" /> DEPLOYMENT_CYCLE
                    </div>
                    <h2 className="text-2xl md:text-4xl font-black tracking-tighter italic uppercase leading-none">EXIT_LOGIC.</h2>
                </div>

                <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
                    <RightCard title="CREDIT_POLICY" desc="Energy credits are non-refundable once the synthesis engine has been engaged." icon={<Activity />} />
                    <RightCard title="SERVICE_HALT" desc="We reserve the right to sever the link for any protocol violations." icon={<Lock />} />
                    <RightCard title="REFUND_GAPS" desc="Refunds are handled on a case-by-case basis within 48 hours of txn." icon={<RefreshCcw />} />
                    <RightCard title="UPTIME_PACT" desc="We aim for 99.9% uptime, but zero liability for scheduled neural maintenance." icon={<BookOpen />} />
                </div>
            </section>

            {/* --- SECTION 5: FINAL TERMINAL --- */}
            <section className="text-center py-12 border-t border-white/5 space-y-8">
                <div className="space-y-3">
                    <span className="text-[10px] font-black text-gray-700 uppercase tracking-[0.6em] font-mono">LAST_HANDSHAKE_UPDATE: 2026_01_15</span>
                    <p className="text-sm text-gray-500 max-w-2xl mx-auto italic">
                        Need clarity on these operational parameters? Connect with our Legal Architects.
                    </p>
                </div>
                <Button variant="ghost" className="px-10 py-6 rounded-xl border-white/5 bg-white/[0.02] text-xs font-black uppercase tracking-widest hover:bg-amber-500 hover:text-white transition-all group">
                    <span className="flex items-center gap-3">
                        CONTACT_LEGAL_TEAM <ArrowRight size={16} className="group-hover:translate-x-2 transition-transform" />
                    </span>
                </Button>
            </section>
        </div>
    )
}

function TermsCard({ icon, title, desc, id, color, active }: any) {
    const colors: any = {
        amber: "text-amber-400 group-hover:bg-amber-500",
        orange: "text-orange-400 group-hover:bg-orange-500",
    }
    return (
        <motion.div
            whileHover={{ y: -6 }}
            className={`p-8 rounded-[2rem] md:rounded-[2.5rem] border transition-all duration-700 group relative overflow-hidden h-full ${active ? 'bg-amber-600/5 border-amber-500/20 shadow-[0_30px_60px_rgba(245,158,11,0.06)]' : 'bg-[#050508] border-white/5 hover:border-amber-500/40'}`}
        >
            <span className="absolute top-8 right-8 text-[9px] font-black uppercase tracking-widest text-gray-800 font-mono">RULE_{id}</span>
            <div className={`w-12 h-12 md:w-14 md:h-14 rounded-2xl flex items-center justify-center mb-8 transition-all duration-500 bg-white/[0.02] border border-white/5 ${colors[color]} group-hover:text-white group-hover:scale-105 group-hover:rotate-12`}>
                {icon}
            </div>
            <div className="space-y-4 text-left">
                <h3 className="text-xl font-black italic tracking-tighter uppercase text-white group-hover:text-amber-400 transition-colors">{title}</h3>
                <p className="text-xs md:text-sm font-medium leading-relaxed text-gray-500 group-hover:text-gray-400 transition-colors">
                    {desc}
                </p>
            </div>
        </motion.div>
    )
}

function RightCard({ title, desc, icon }: any) {
    return (
        <div className="p-6 md:p-8 rounded-[2rem] bg-[#050508] border border-white/5 hover:border-amber-500/30 transition-all group flex flex-col items-center text-center space-y-4">
            <div className="w-10 h-10 rounded-xl bg-white/5 flex items-center justify-center text-gray-700 group-hover:text-amber-500 group-hover:bg-amber-500/10 transition-all">
                {icon}
            </div>
            <h4 className="text-xs md:text-sm font-black italic uppercase tracking-tighter group-hover:text-white">{title}</h4>
            <p className="text-[9px] text-gray-600 font-bold leading-relaxed">{desc}</p>
        </div>
    )
}
