export default function Terms() {
    return (
        <div className="py-24 px-6 max-w-3xl mx-auto text-white">
            <h1 className="text-4xl font-black mb-2">Terms & Conditions</h1>
            <p className="text-gray-500 font-mono text-sm mb-12 uppercase tracking-wider">Last Updated: December 25, 2025</p>

            <div className="space-y-12 text-gray-300 leading-relaxed">
                <section className="space-y-4">
                    <p className="text-lg font-medium text-white">
                        Welcome to FutureBuilder. By accessing our platform, you agree to the following terms and conditions.
                    </p>
                </section>

                <section className="space-y-4">
                    <h3 className="text-xl font-bold text-white border-b border-white/10 pb-4 mb-4">1. Acceptance of Terms</h3>
                    <p>By using our services, you agree to be bound by these terms. If you do not agree, strictly do not use the platform.</p>
                </section>

                <section className="space-y-4">
                    <h3 className="text-xl font-bold text-white border-b border-white/10 pb-4 mb-4">2. User Accounts</h3>
                    <p>
                        You are responsible for maintaining the security of your account credentials. Any activity under your account is your responsibility.
                        You agree to notify us immediately of any unauthorized use of your account.
                    </p>
                </section>

                <section className="space-y-4">
                    <h3 className="text-xl font-bold text-white border-b border-white/10 pb-4 mb-4">3. Acceptable Use</h3>
                    <p>You may not use our platform to:</p>
                    <ul className="list-disc pl-6 space-y-2 text-gray-400">
                        <li>Generate content that is illegal, harmful, or discriminatory.</li>
                        <li>Reverse engineer or attempt to extract the source code of the platform.</li>
                        <li>Spam or harass other users.</li>
                    </ul>
                </section>

                <section className="space-y-4">
                    <h3 className="text-xl font-bold text-white border-b border-white/10 pb-4 mb-4">4. Intellectual Property</h3>
                    <p>
                        All content generated by FutureBuilder's core engine remains the intellectual property of FutureBuilder.
                        Your personal data and specific inputs remain your property.
                    </p>
                </section>

                <section className="space-y-4">
                    <h3 className="text-xl font-bold text-white border-b border-white/10 pb-4 mb-4">5. Disclaimer</h3>
                    <p>
                        FutureBuilder provides career planning "as is". While we use advanced data analysis, we do not guarantee specific employment outcomes, salary increases, or academic acceptance.
                    </p>
                </section>

                <section className="space-y-4">
                    <h3 className="text-xl font-bold text-white border-b border-white/10 pb-4 mb-4">6. Changes to Terms</h3>
                    <p>We reserve the right to modify these terms at any time. Continued use of the platform constitutes acceptance of updated terms.</p>
                </section>
            </div>
        </div>
    )
}
