/**
 * ============================================================
 *  PACKAGER — Phase D Export Factory
 *  Creates the final deliverable ZIP archive containing:
 *  ✅ All generated code (backend, admin, frontend)
 *  ✅ project-report.docx
 *  ✅ presentation.pptx
 *  ✅ README.md + setup.sh
 *  Uses: archiver npm library (most reliable Node.js zipper)
 * ============================================================
 */
import * as fs from 'fs';
import * as path from 'path';

export const createProjectZip = async (
    projectId: string,
    projectDir: string,   // disk path where all files were written
    outputDir: string,    // where to write the final zip
    title: string
): Promise<string | null> => {
    try {
        const archiver = (await import('archiver')).default;
        const safeTitle = title.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase().slice(0, 40);
        // Move output to parent directory to avoid circular zipping (Fixes Windows Access Denied)
        const zipOutPath = path.join(path.dirname(outputDir), `${safeTitle}-complete.zip`);
        const output = fs.createWriteStream(zipOutPath);

        const archive = archiver('zip', { zlib: { level: 9 } });

        await new Promise<void>((resolve, reject) => {
            output.on('close', resolve);
            output.on('error', reject);
            archive.on('error', reject);

            archive.pipe(output);

            // Add entire project code directory
            if (fs.existsSync(projectDir)) {
                archive.directory(projectDir, safeTitle);
            }

            archive.finalize();
        });

        return zipOutPath;
    } catch (e: any) {
        console.error('PACKAGER_ERROR:', e.message);
        return null;
    }
};

// ─── SETUP SCRIPT GENERATOR ──────────────────────────────────────────────────
export const generateSetupScript = (
    title: string,
    be: string,
    db: string,
    fe: string,
): string => {
    const isNode = be.toLowerCase().includes('node') || be.toLowerCase().includes('express');
    const isPython = be.toLowerCase().includes('python') || be.toLowerCase().includes('fastapi');
    const isMongo = db.toLowerCase().includes('mongo');
    const safeTitle = title.replace(/[^a-zA-Z0-9 ]/g, '');

    let beInstall = isNode ? 'npm install' : (isPython ? 'pip install -r requirements.txt' : 'npm install');
    let beStart = isNode ? 'npm run dev' : (isPython ? 'uvicorn main:app --reload --port 5000' : 'npm start');
    let dbSetup = isMongo ? '# Ensure MongoDB is running: mongod --dbpath ./data' : '# Ensure your SQL database server is running';

    return `#!/bin/bash
# ============================================================
# 🚀 AUTO SETUP SCRIPT — ${safeTitle}
# Generated by Universal AI Build Engine
# ============================================================

echo "🔧 Setting up ${safeTitle}..."
echo ""

# Step 1: Backend Setup
echo "📦 Installing Backend dependencies..."
cd backend
${beInstall}
cd ..
echo "✅ Backend installed"
echo ""

# Step 2: Admin Panel Setup
echo "🎛️ Installing Admin Panel dependencies..."
cd admin
npm install
cd ..
echo "✅ Admin installed"
echo ""

# Step 3: Frontend Setup
echo "🎨 Installing Frontend dependencies..."
cd frontend
npm install
cd ..
echo "✅ Frontend installed"
echo ""

# Step 4: Database
echo "📌 Database Setup:"
echo "${dbSetup}"
echo ""

# Step 5: Environment
echo "⚙️ IMPORTANT: Configure .env files before starting!"
echo "  backend/.env → MONGO_URI / DB_URI, JWT_SECRET, PORT=5000"
echo ""

echo "=========================================="
echo "🟢 Start Guide:"
echo "  Terminal 1 → cd backend && ${beStart}"
echo "  Terminal 2 → cd admin && npm run dev   (Admin: http://localhost:3001)"
echo "  Terminal 3 → cd frontend && npm run dev (App: http://localhost:3000)"
echo "=========================================="
echo ""
echo "✅ ${safeTitle} is ready to use!"
`;
};

// ─── ENV EXAMPLE GENERATOR ───────────────────────────────────────────────────
export const generateEnvExample = (db: string, title: string): string => {
    const isMongo = db.toLowerCase().includes('mongo');
    const isSql = db.toLowerCase().includes('postgres') || db.toLowerCase().includes('mysql');
    const safeTitle = title.toLowerCase().replace(/[^a-z0-9]/g, '_').slice(0, 20);
    return `# ============================================================
# .env.example — ${title}
# Copy this file to .env and fill in your actual values
# ============================================================

# Server
PORT=5000
NODE_ENV=development

# JWT
JWT_SECRET=your_very_secure_jwt_secret_key_here_min_32_chars
JWT_EXPIRES_IN=7d

${isMongo ? `# MongoDB
MONGO_URI=mongodb://localhost:27017/${safeTitle}_db` : ''}
${isSql ? `# SQL Database
DB_HOST=localhost
DB_PORT=5432
DB_NAME=${safeTitle}_db
DB_USER=your_db_user
DB_PASS=your_db_password` : ''}

# Admin Credentials (for seeding)
ADMIN_EMAIL=admin@${safeTitle}.com
ADMIN_PASSWORD=Admin@123

# Frontend URLs (for CORS)
FRONTEND_URL=http://localhost:3000
ADMIN_URL=http://localhost:3001
`;
};
